//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Window.Wpf.ShipTrainingPlanner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShipTrainingPlanner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipTrainingPlanner() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Window.Wpf.ShipTrainingPlanner.ShipTrainingPlanner", typeof(ShipTrainingPlanner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        internal static string AddShip {
            get {
                return ResourceManager.GetString("AddShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜.
        /// </summary>
        internal static string ASWBonus {
            get {
                return ResourceManager.GetString("ASWBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜現在.
        /// </summary>
        internal static string ASWBonusCurrent {
            get {
                return ResourceManager.GetString("ASWBonusCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜目標.
        /// </summary>
        internal static string ASWBonusTarget {
            get {
                return ResourceManager.GetString("ASWBonusTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜合計現在.
        /// </summary>
        internal static string ASWCurrent {
            get {
                return ResourceManager.GetString("ASWCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜残.
        /// </summary>
        internal static string ASWRemaining {
            get {
                return ResourceManager.GetString("ASWRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜合計目標.
        /// </summary>
        internal static string ASWTarget {
            get {
                return ResourceManager.GetString("ASWTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示完了.
        /// </summary>
        internal static string DisplayFinished {
            get {
                return ResourceManager.GetString("DisplayFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編集.
        /// </summary>
        internal static string EditPlan {
            get {
                return ResourceManager.GetString("EditPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp..
        /// </summary>
        internal static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 耐久.
        /// </summary>
        internal static string HPBonus {
            get {
                return ResourceManager.GetString("HPBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (HP bonus (Current)).
        /// </summary>
        internal static string HPBonusCurrent {
            get {
                return ResourceManager.GetString("HPBonusCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (HP bonus (Target)).
        /// </summary>
        internal static string HPBonusTarget {
            get {
                return ResourceManager.GetString("HPBonusTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (HP (Current)).
        /// </summary>
        internal static string HPCurrent {
            get {
                return ResourceManager.GetString("HPCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (HP (Remaining)).
        /// </summary>
        internal static string HPRemaining {
            get {
                return ResourceManager.GetString("HPRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (HP (Target)).
        /// </summary>
        internal static string HPTarget {
            get {
                return ResourceManager.GetString("HPTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv.
        /// </summary>
        internal static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Level (Current)).
        /// </summary>
        internal static string LevelCurrent {
            get {
                return ResourceManager.GetString("LevelCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Level (Target)).
        /// </summary>
        internal static string LevelTarget {
            get {
                return ResourceManager.GetString("LevelTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Luck (Current)).
        /// </summary>
        internal static string LuckCurrent {
            get {
                return ResourceManager.GetString("LuckCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Luck (Remaining)).
        /// </summary>
        internal static string LuckRemaining {
            get {
                return ResourceManager.GetString("LuckRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Luck (Target)).
        /// </summary>
        internal static string LuckTarget {
            get {
                return ResourceManager.GetString("LuckTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべての改造について通知する.
        /// </summary>
        internal static string NotifyAnyRemodelReady {
            get {
                return ResourceManager.GetString("NotifyAnyRemodelReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例：レベル1から神風をレベルアップして神風改二に改造しようとした場合
        ///無効にすると、神風を神風改二に改造できるときだけ通知されます
        ///有効にすると、神風を神風改に改造できるときと、神風改を神風改二に改造できるときに通知されます.
        /// </summary>
        internal static string NotifyAnyRemodelReadyToolTip {
            get {
                return ResourceManager.GetString("NotifyAnyRemodelReadyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 優先順位.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? (Remaining exp.).
        /// </summary>
        internal static string RemainingExp {
            get {
                return ResourceManager.GetString("RemainingExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造.
        /// </summary>
        internal static string RemodelGoal {
            get {
                return ResourceManager.GetString("RemodelGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了除去.
        /// </summary>
        internal static string RemoveFinishedPlans {
            get {
                return ResourceManager.GetString("RemoveFinishedPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 除去.
        /// </summary>
        internal static string RemovePlan {
            get {
                return ResourceManager.GetString("RemovePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘訓練.
        /// </summary>
        internal static string ViewerTitle {
            get {
                return ResourceManager.GetString("ViewerTitle", resourceCulture);
            }
        }
    }
}
