//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KancolleProgress {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KancolleProgressResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KancolleProgressResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KancolleProgress.KancolleProgressResources", typeof(KancolleProgressResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コレクション.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カラーフィルター.
        /// </summary>
        public static string ColorFilters {
            get {
                return ResourceManager.GetString("ColorFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大発.
        /// </summary>
        public static string Daihatsu {
            get {
                return ResourceManager.GetString("Daihatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大発&amp;内火艇.
        /// </summary>
        public static string DaihatsuAndTank {
            get {
                return ResourceManager.GetString("DaihatsuAndTank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イベント.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVエクスポート.
        /// </summary>
        public static string ExportAsCsv {
            get {
                return ResourceManager.GetString("ExportAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 司令部.
        /// </summary>
        public static string Fcf {
            get {
                return ResourceManager.GetString("Fcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル(_F).
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カンスト.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行方不明.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 先制対潜.
        /// </summary>
        public static string NoSonarOpeningAsw {
            get {
                return ResourceManager.GetString("NoSonarOpeningAsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘.
        /// </summary>
        public static string Ships {
            get {
                return ResourceManager.GetString("Ships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1スロ先制対潜.
        /// </summary>
        public static string SingleSonarOpeningAsw {
            get {
                return ResourceManager.GetString("SingleSonarOpeningAsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内火艇.
        /// </summary>
        public static string Tank {
            get {
                return ResourceManager.GetString("Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これ進捗.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示(_V).
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
