//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceRecord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceRecord() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.ResourceRecord", typeof(ResourceRecord).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵基地空襲.
        /// </summary>
        public static string EnemyFleetRecord_EnemyAirRaid {
            get {
                return ResourceManager.GetString("EnemyFleetRecord_EnemyAirRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコード {0} の読み込みに失敗しました。.
        /// </summary>
        public static string RecordBase_FailedToLoadRecord {
            get {
                return ResourceManager.GetString("RecordBase_FailedToLoadRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコード {0} の書き込みに失敗しました。.
        /// </summary>
        public static string RecordBase_FailedToWriteRecord {
            get {
                return ResourceManager.GetString("RecordBase_FailedToWriteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコード {0} は存在しません。.
        /// </summary>
        public static string RecordBase_RecordDoesNotExist {
            get {
                return ResourceManager.GetString("RecordBase_RecordDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコードのセーブに失敗しました。.
        /// </summary>
        public static string RecordManager_FailedToSaveRecords {
            get {
                return ResourceManager.GetString("RecordManager_FailedToSaveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコードをセーブしました。.
        /// </summary>
        public static string RecordManager_RecordsSaved {
            get {
                return ResourceManager.GetString("RecordManager_RecordsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipParameter: {0} の対潜値が予測範囲から外れました( [{1} ~ {2}] ~ {3} )。.
        /// </summary>
        public static string ShipParameterRecord_AswOutOfPredictedRange {
            get {
                return ResourceManager.GetString("ShipParameterRecord_AswOutOfPredictedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipParameter: {0} の回避値が予測範囲から外れました( [{1} ~ {2}] ~ {3} )。.
        /// </summary>
        public static string ShipParameterRecord_EvasionOutOfPredictedRange {
            get {
                return ResourceManager.GetString("ShipParameterRecord_EvasionOutOfPredictedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipParameter: {0} の索敵値が予測範囲から外れました( [{1} ~ {2}] ~ {3} )。.
        /// </summary>
        public static string ShipParameterRecord_LosOutOfPredictedRange {
            get {
                return ResourceManager.GetString("ShipParameterRecord_LosOutOfPredictedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} の初期装備が更新されました。.
        /// </summary>
        public static string ShipParameterRecord_StockEquipmentUpdated {
            get {
                return ResourceManager.GetString("ShipParameterRecord_StockEquipmentUpdated", resourceCulture);
            }
        }
    }
}
