//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConstantsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConstantsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Data.ConstantsRes", typeof(ConstantsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高射装置.
        /// </summary>
        internal static string AADirector {
            get {
                return ResourceManager.GetString("AADirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 集中機銃.
        /// </summary>
        internal static string AAGun {
            get {
                return ResourceManager.GetString("AAGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提督.
        /// </summary>
        internal static string Admiral {
            get {
                return ResourceManager.GetString("Admiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空撃.
        /// </summary>
        internal static string AirAttack {
            get {
                return ResourceManager.GetString("AirAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空戦.
        /// </summary>
        internal static string AirBattle {
            get {
                return ResourceManager.GetString("AirBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 防空.
        /// </summary>
        internal static string AirDefense {
            get {
                return ResourceManager.GetString("AirDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空劣勢.
        /// </summary>
        internal static string AirDenialNew {
            get {
                return ResourceManager.GetString("AirDenialNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空権喪失.
        /// </summary>
        internal static string AirIncapability {
            get {
                return ResourceManager.GetString("AirIncapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空均衡.
        /// </summary>
        internal static string AirParity {
            get {
                return ResourceManager.GetString("AirParity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空襲戦.
        /// </summary>
        internal static string AirRaid {
            get {
                return ResourceManager.GetString("AirRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空優勢.
        /// </summary>
        internal static string AirSuperiority {
            get {
                return ResourceManager.GetString("AirSuperiority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空権確保.
        /// </summary>
        internal static string AirSupremacy {
            get {
                return ResourceManager.GetString("AirSupremacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 弾薬.
        /// </summary>
        internal static string Ammo {
            get {
                return ResourceManager.GetString("Ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水.
        /// </summary>
        internal static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一警戒.
        /// </summary>
        internal static string ASWFormation {
            get {
                return ResourceManager.GetString("ASWFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提督経験値: +{0}.
        /// </summary>
        internal static string BattleDetail_AdmiralExp {
            get {
                return ResourceManager.GetString("BattleDetail_AdmiralExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 味方基地航空隊 参加中隊:.
        /// </summary>
        internal static string BattleDetail_AirAttackUnits {
            get {
                return ResourceManager.GetString("BattleDetail_AirAttackUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〈第{0}波〉.
        /// </summary>
        internal static string BattleDetail_AirAttackWave {
            get {
                return ResourceManager.GetString("BattleDetail_AirAttackWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  〈基地航空隊〉 .
        /// </summary>
        internal static string BattleDetail_AirBase {
            get {
                return ResourceManager.GetString("BattleDetail_AirBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵軍触接.
        /// </summary>
        internal static string BattleDetail_AirBaseEnemyContact {
            get {
                return ResourceManager.GetString("BattleDetail_AirBaseEnemyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自軍触接.
        /// </summary>
        internal static string BattleDetail_AirBaseFriendlyContact {
            get {
                return ResourceManager.GetString("BattleDetail_AirBaseFriendlyContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}基地.
        /// </summary>
        internal static string BattleDetail_Base {
            get {
                return ResourceManager.GetString("BattleDetail_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 《戦闘終了》.
        /// </summary>
        internal static string BattleDetail_BattleEnd {
            get {
                return ResourceManager.GetString("BattleDetail_BattleEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (ボス).
        /// </summary>
        internal static string BattleDetail_Boss {
            get {
                return ResourceManager.GetString("BattleDetail_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドロップ：.
        /// </summary>
        internal static string BattleDetail_Drop {
            get {
                return ResourceManager.GetString("BattleDetail_Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  〈敵随伴艦隊〉.
        /// </summary>
        internal static string BattleDetail_EnemyEscortFleet {
            get {
                return ResourceManager.GetString("BattleDetail_EnemyEscortFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  〈敵艦隊〉 .
        /// </summary>
        internal static string BattleDetail_EnemyFleet {
            get {
                return ResourceManager.GetString("BattleDetail_EnemyFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  〈敵主力艦隊〉.
        /// </summary>
        internal static string BattleDetail_EnemyMainFleet {
            get {
                return ResourceManager.GetString("BattleDetail_EnemyMainFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵軍夜間触接: .
        /// </summary>
        internal static string BattleDetail_EnemyNightContact {
            get {
                return ResourceManager.GetString("BattleDetail_EnemyNightContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵軍探照灯照射: {0} #{1}.
        /// </summary>
        internal static string BattleDetail_EnemySearchlight {
            get {
                return ResourceManager.GetString("BattleDetail_EnemySearchlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵軍照明弾投射: {0} #{1}.
        /// </summary>
        internal static string BattleDetail_EnemyStarshell {
            get {
                return ResourceManager.GetString("BattleDetail_EnemyStarshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - 火力{0}, 雷装{1}, 対空{2}, 装甲{3}.
        /// </summary>
        internal static string BattleDetail_EnemyStats {
            get {
                return ResourceManager.GetString("BattleDetail_EnemyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交戦形態: .
        /// </summary>
        internal static string BattleDetail_EngagementForm {
            get {
                return ResourceManager.GetString("BattleDetail_EngagementForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  / 敵軍陣形: .
        /// </summary>
        internal static string BattleDetail_FormationEnemy {
            get {
                return ResourceManager.GetString("BattleDetail_FormationEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自軍陣形: .
        /// </summary>
        internal static string BattleDetail_FormationFriend {
            get {
                return ResourceManager.GetString("BattleDetail_FormationFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  〈味方随伴艦隊〉 .
        /// </summary>
        internal static string BattleDetail_FriendEscortFleet {
            get {
                return ResourceManager.GetString("BattleDetail_FriendEscortFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  〈味方艦隊〉 .
        /// </summary>
        internal static string BattleDetail_FriendFleet {
            get {
                return ResourceManager.GetString("BattleDetail_FriendFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自軍夜間触接: .
        /// </summary>
        internal static string BattleDetail_FriendlyNightContact {
            get {
                return ResourceManager.GetString("BattleDetail_FriendlyNightContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自軍探照灯照射: {0} #{1}.
        /// </summary>
        internal static string BattleDetail_FriendlySearchlight {
            get {
                return ResourceManager.GetString("BattleDetail_FriendlySearchlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自軍照明弾投射: {0} #{1}.
        /// </summary>
        internal static string BattleDetail_FriendlyStarshell {
            get {
                return ResourceManager.GetString("BattleDetail_FriendlyStarshell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  〈味方主力艦隊〉 .
        /// </summary>
        internal static string BattleDetail_FriendMainFleet {
            get {
                return ResourceManager.GetString("BattleDetail_FriendMainFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   : 装甲破壊.
        /// </summary>
        internal static string BattleDetail_IsBossDamaged {
            get {
                return ResourceManager.GetString("BattleDetail_IsBossDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  セル: .
        /// </summary>
        internal static string BattleDetail_Node {
            get {
                return ResourceManager.GetString("BattleDetail_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◆ 戦闘結果 ◆.
        /// </summary>
        internal static string BattleDetail_Result {
            get {
                return ResourceManager.GetString("BattleDetail_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVP(随伴艦隊): {0}.
        /// </summary>
        internal static string BattleDetail_ResultMVPEscort {
            get {
                return ResourceManager.GetString("BattleDetail_ResultMVPEscort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MVP(主力艦隊): {0}.
        /// </summary>
        internal static string BattleDetail_ResultMVPMain {
            get {
                return ResourceManager.GetString("BattleDetail_ResultMVPMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ランク: {0}.
        /// </summary>
        internal static string BattleDetail_ResultRank {
            get {
                return ResourceManager.GetString("BattleDetail_ResultRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  / 敵軍索敵: .
        /// </summary>
        internal static string BattleDetail_SearchingEnemy {
            get {
                return ResourceManager.GetString("BattleDetail_SearchingEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自軍索敵: .
        /// </summary>
        internal static string BattleDetail_SearchingFriend {
            get {
                return ResourceManager.GetString("BattleDetail_SearchingFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘基本経験値: +{1}.
        /// </summary>
        internal static string BattleDetail_ShipExp {
            get {
                return ResourceManager.GetString("BattleDetail_ShipExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}: {1} {2} HP: {3} / {4} - 火力{5}, 雷装{6}, 対空{7}, 装甲{8}.
        /// </summary>
        internal static string BattleDetail_ShipStats {
            get {
                return ResourceManager.GetString("BattleDetail_ShipStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空カットイン ( {0}, {1}({2}) ).
        /// </summary>
        internal static string BattleDetail_Stage2AACI {
            get {
                return ResourceManager.GetString("BattleDetail_Stage2AACI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 《{0}》.
        /// </summary>
        internal static string BattleDetail_TitleBrackets {
            get {
                return ResourceManager.GetString("BattleDetail_TitleBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第四警戒.
        /// </summary>
        internal static string BattleForm {
            get {
                return ResourceManager.GetString("BattleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボーキサイト.
        /// </summary>
        internal static string Baux {
            get {
                return ResourceManager.GetString("Baux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空戦.
        /// </summary>
        internal static string BGM_BattleAir {
            get {
                return ResourceManager.GetString("BGM_BattleAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボス戦.
        /// </summary>
        internal static string BGM_BattleBoss {
            get {
                return ResourceManager.GetString("BGM_BattleBoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼戦.
        /// </summary>
        internal static string BGM_BattleDay {
            get {
                return ResourceManager.GetString("BGM_BattleDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜戦.
        /// </summary>
        internal static string BGM_BattleNight {
            get {
                return ResourceManager.GetString("BGM_BattleNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃中.
        /// </summary>
        internal static string BGM_Sortie {
            get {
                return ResourceManager.GetString("BGM_Sortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大口径主砲.
        /// </summary>
        internal static string BigGun {
            get {
                return ResourceManager.GetString("BigGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 青.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爆撃.
        /// </summary>
        internal static string BombingAttack {
            get {
                return ResourceManager.GetString("BombingAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速修復材.
        /// </summary>
        internal static string Bucket {
            get {
                return ResourceManager.GetString("Bucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大佐.
        /// </summary>
        internal static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中佐.
        /// </summary>
        internal static string Commander {
            get {
                return ResourceManager.GetString("Commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コモン.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠.
        /// </summary>
        internal static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大破.
        /// </summary>
        internal static string CriticalDamage {
            get {
                return ResourceManager.GetString("CriticalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カットイン.
        /// </summary>
        internal static string CutIn {
            get {
                return ResourceManager.GetString("CutIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸攻撃(大発動艇).
        /// </summary>
        internal static string DaihatsuAttack {
            get {
                return ResourceManager.GetString("DaihatsuAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 損壊.
        /// </summary>
        internal static string Damaged {
            get {
                return ResourceManager.GetString("Damaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼夜戦.
        /// </summary>
        internal static string DayBattle {
            get {
                return ResourceManager.GetString("DayBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爆雷攻撃.
        /// </summary>
        internal static string DepthChargeAttack {
            get {
                return ResourceManager.GetString("DepthChargeAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 破壊.
        /// </summary>
        internal static string Destroyed {
            get {
                return ResourceManager.GetString("Destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開発資材.
        /// </summary>
        internal static string DevMat {
            get {
                return ResourceManager.GetString("DevMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輪形陣.
        /// </summary>
        internal static string Diamond {
            get {
                return ResourceManager.GetString("Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 混乱.
        /// </summary>
        internal static string Disorder {
            get {
                return ResourceManager.GetString("Disorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連続射撃.
        /// </summary>
        internal static string DoubleAttack {
            get {
                return ResourceManager.GetString("DoubleAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複縦陣.
        /// </summary>
        internal static string DoubleLine {
            get {
                return ResourceManager.GetString("DoubleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 丙.
        /// </summary>
        internal static string EasyDifficulty {
            get {
                return ResourceManager.GetString("EasyDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梯形陣.
        /// </summary>
        internal static string Echelon {
            get {
                return ResourceManager.GetString("Echelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵連合.
        /// </summary>
        internal static string EnemyCombinedFleet {
            get {
                return ResourceManager.GetString("EnemyCombinedFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXホロ.
        /// </summary>
        internal static string EXHolo {
            get {
                return ResourceManager.GetString("EXHolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征.
        /// </summary>
        internal static string Expedition {
            get {
                return ResourceManager.GetString("Expedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征結果.
        /// </summary>
        internal static string ExpeditionResult {
            get {
                return ResourceManager.GetString("ExpeditionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失敗(非索敵機).
        /// </summary>
        internal static string FailureNoPlane {
            get {
                return ResourceManager.GetString("FailureNoPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速.
        /// </summary>
        internal static string Fast {
            get {
                return ResourceManager.GetString("Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第一警戒航行序列.
        /// </summary>
        internal static string FirstPatrolFormation {
            get {
                return ResourceManager.GetString("FirstPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速建造材.
        /// </summary>
        internal static string Flamethrower {
            get {
                return ResourceManager.GetString("Flamethrower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元帥.
        /// </summary>
        internal static string FleetAdmiral {
            get {
                return ResourceManager.GetString("FleetAdmiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編成.
        /// </summary>
        internal static string Formation {
            get {
                return ResourceManager.GetString("Formation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二警戒.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大将.
        /// </summary>
        internal static string FourStarAdmiral {
            get {
                return ResourceManager.GetString("FourStarAdmiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第四警戒航行序列.
        /// </summary>
        internal static string FourthPatrolFormation {
            get {
                return ResourceManager.GetString("FourthPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 燃料.
        /// </summary>
        internal static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 家具コイン.
        /// </summary>
        internal static string FurnitureCoin {
            get {
                return ResourceManager.GetString("FurnitureCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大成功.
        /// </summary>
        internal static string GreatSuccess {
            get {
                return ResourceManager.GetString("GreatSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高角砲x2.
        /// </summary>
        internal static string HA2 {
            get {
                return ResourceManager.GetString("HA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高角砲+高射装置.
        /// </summary>
        internal static string HAAAD {
            get {
                return ResourceManager.GetString("HAAAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高角砲.
        /// </summary>
        internal static string HAGun {
            get {
                return ResourceManager.GetString("HAGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 甲.
        /// </summary>
        internal static string HardDifficulty {
            get {
                return ResourceManager.GetString("HardDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反航戦.
        /// </summary>
        internal static string HeadOn {
            get {
                return ResourceManager.GetString("HeadOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 健在.
        /// </summary>
        internal static string Healthy {
            get {
                return ResourceManager.GetString("Healthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホロ.
        /// </summary>
        internal static string Holo {
            get {
                return ResourceManager.GetString("Holo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 時報.
        /// </summary>
        internal static string Hourly {
            get {
                return ResourceManager.GetString("Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 放置.
        /// </summary>
        internal static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 気のせいだった.
        /// </summary>
        internal static string Imagination {
            get {
                return ResourceManager.GetString("Imagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修資材.
        /// </summary>
        internal static string ImpMat {
            get {
                return ResourceManager.GetString("ImpMat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 藍.
        /// </summary>
        internal static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 損害.
        /// </summary>
        internal static string Injured {
            get {
                return ResourceManager.GetString("Injured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 変.
        /// </summary>
        internal static string Irregular {
            get {
                return ResourceManager.GetString("Irregular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 陸上.
        /// </summary>
        internal static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸地点.
        /// </summary>
        internal static string LandNode {
            get {
                return ResourceManager.GetString("LandNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 船団護衛成功.
        /// </summary>
        internal static string LargeResourceNode {
            get {
                return ResourceManager.GetString("LargeResourceNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レーザー攻撃.
        /// </summary>
        internal static string Laser {
            get {
                return ResourceManager.GetString("Laser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小破.
        /// </summary>
        internal static string LightDamage {
            get {
                return ResourceManager.GetString("LightDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単横陣.
        /// </summary>
        internal static string LineAbreast {
            get {
                return ResourceManager.GetString("LineAbreast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単縦陣.
        /// </summary>
        internal static string LineAhead {
            get {
                return ResourceManager.GetString("LineAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 長.
        /// </summary>
        internal static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵.
        /// </summary>
        internal static string LOS {
            get {
                return ResourceManager.GetString("LOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少佐.
        /// </summary>
        internal static string LtCmdr {
            get {
                return ResourceManager.GetString("LtCmdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渦潮.
        /// </summary>
        internal static string Maelstrom {
            get {
                return ResourceManager.GetString("Maelstrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (主砲x3).
        /// </summary>
        internal static string Main3 {
            get {
                return ResourceManager.GetString("Main3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (主砲/徹甲).
        /// </summary>
        internal static string MainAP {
            get {
                return ResourceManager.GetString("MainAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (主砲/主砲).
        /// </summary>
        internal static string MainMain {
            get {
                return ResourceManager.GetString("MainMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (主砲x2/副砲).
        /// </summary>
        internal static string MainMainSec {
            get {
                return ResourceManager.GetString("MainMainSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (主砲/電探).
        /// </summary>
        internal static string MainRadar {
            get {
                return ResourceManager.GetString("MainRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (主砲/副砲).
        /// </summary>
        internal static string MainSecondary {
            get {
                return ResourceManager.GetString("MainSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (主砲/魚雷).
        /// </summary>
        internal static string MainTorp {
            get {
                return ResourceManager.GetString("MainTorp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 乙.
        /// </summary>
        internal static string MediumDifficulty {
            get {
                return ResourceManager.GetString("MediumDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃.
        /// </summary>
        internal static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中破.
        /// </summary>
        internal static string ModerateDamage {
            get {
                return ResourceManager.GetString("ModerateDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改装.
        /// </summary>
        internal static string Modernization {
            get {
                return ResourceManager.GetString("Modernization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜戦.
        /// </summary>
        internal static string NightBattle {
            get {
                return ResourceManager.GetString("NightBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜昼戦.
        /// </summary>
        internal static string NightDayBattle {
            get {
                return ResourceManager.GetString("NightDayBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非戦闘.
        /// </summary>
        internal static string NoBattle {
            get {
                return ResourceManager.GetString("NoBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        internal static string NoNode {
            get {
                return ResourceManager.GetString("NoNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 獲得資源なし.
        /// </summary>
        internal static string NoResources {
            get {
                return ResourceManager.GetString("NoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未帰還.
        /// </summary>
        internal static string NoReturn {
            get {
                return ResourceManager.GetString("NoReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常艦隊.
        /// </summary>
        internal static string NormalFleet {
            get {
                return ResourceManager.GetString("NormalFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新米中佐.
        /// </summary>
        internal static string NoviceCommander {
            get {
                return ResourceManager.GetString("NoviceCommander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新米少佐.
        /// </summary>
        internal static string NoviceLtCmdr {
            get {
                return ResourceManager.GetString("NoviceLtCmdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同航戦.
        /// </summary>
        internal static string Parallel {
            get {
                return ResourceManager.GetString("Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 母港.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 演習.
        /// </summary>
        internal static string Practice {
            get {
                return ResourceManager.GetString("Practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他.
        /// </summary>
        internal static string QuestOther {
            get {
                return ResourceManager.GetString("QuestOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電探.
        /// </summary>
        internal static string Radar {
            get {
                return ResourceManager.GetString("Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虹.
        /// </summary>
        internal static string Rainbow {
            get {
                return ResourceManager.GetString("Rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レア.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 少将.
        /// </summary>
        internal static string RearAdmiral {
            get {
                return ResourceManager.GetString("RearAdmiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 赤.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 休息.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退避.
        /// </summary>
        internal static string Retreated {
            get {
                return ResourceManager.GetString("Retreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三警戒.
        /// </summary>
        internal static string Ring {
            get {
                return ResourceManager.GetString("Ring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロケット砲撃.
        /// </summary>
        internal static string RocketAttack {
            get {
                return ResourceManager.GetString("RocketAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桜虹.
        /// </summary>
        internal static string Sakura {
            get {
                return ResourceManager.GetString("Sakura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第二警戒航行序列.
        /// </summary>
        internal static string SecondPatrolFormation {
            get {
                return ResourceManager.GetString("SecondPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 砲撃.
        /// </summary>
        internal static string Shelling {
            get {
                return ResourceManager.GetString("Shelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘.
        /// </summary>
        internal static string ShipGirl {
            get {
                return ResourceManager.GetString("ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sホロ.
        /// </summary>
        internal static string SHolo {
            get {
                return ResourceManager.GetString("SHolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 短.
        /// </summary>
        internal static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 銀.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 低速.
        /// </summary>
        internal static string Slow {
            get {
                return ResourceManager.GetString("Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出撃.
        /// </summary>
        internal static string Sortie {
            get {
                return ResourceManager.GetString("Sortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特殊放置.
        /// </summary>
        internal static string SpecialIdle {
            get {
                return ResourceManager.GetString("SpecialIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輝虹.
        /// </summary>
        internal static string SRainbow {
            get {
                return ResourceManager.GetString("SRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSホロ.
        /// </summary>
        internal static string SSHolo {
            get {
                return ResourceManager.GetString("SSHolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSホロ+.
        /// </summary>
        internal static string SSHoloPlus {
            get {
                return ResourceManager.GetString("SSHoloPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 待機.
        /// </summary>
        internal static string Standby {
            get {
                return ResourceManager.GetString("Standby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初期位置.
        /// </summary>
        internal static string StartNode {
            get {
                return ResourceManager.GetString("StartNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 鋼材.
        /// </summary>
        internal static string Steel {
            get {
                return ResourceManager.GetString("Steel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功(非索敵機).
        /// </summary>
        internal static string SuccessNoPlane {
            get {
                return ResourceManager.GetString("SuccessNoPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功(未帰還有).
        /// </summary>
        internal static string SuccessNoReturn {
            get {
                return ResourceManager.GetString("SuccessNoReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撃沈.
        /// </summary>
        internal static string Sunk {
            get {
                return ResourceManager.GetString("Sunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補給.
        /// </summary>
        internal static string Supply {
            get {
                return ResourceManager.GetString("Supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水上部隊.
        /// </summary>
        internal static string SurfaceFleet {
            get {
                return ResourceManager.GetString("SurfaceFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T字有利.
        /// </summary>
        internal static string TAdvantage {
            get {
                return ResourceManager.GetString("TAdvantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退避.
        /// </summary>
        internal static string TakeCover {
            get {
                return ResourceManager.GetString("TakeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸攻撃(内火艇).
        /// </summary>
        internal static string TankAttack {
            get {
                return ResourceManager.GetString("TankAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 機動部隊.
        /// </summary>
        internal static string TaskForce {
            get {
                return ResourceManager.GetString("TaskForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T字不利.
        /// </summary>
        internal static string TDisadvantage {
            get {
                return ResourceManager.GetString("TDisadvantage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第三警戒航行序列.
        /// </summary>
        internal static string ThirdPatrolFormation {
            get {
                return ResourceManager.GetString("ThirdPatrolFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基地空襲戦.
        /// </summary>
        internal static string Title_BaseAirRaid {
            get {
                return ResourceManager.GetString("Title_BaseAirRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連合艦隊-機動部隊 対連合艦隊 昼戦.
        /// </summary>
        internal static string Title_CombinedEachDay {
            get {
                return ResourceManager.GetString("Title_CombinedEachDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連合艦隊-水上部隊 対連合艦隊 昼戦.
        /// </summary>
        internal static string Title_CombinedEachWater {
            get {
                return ResourceManager.GetString("Title_CombinedEachWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連合艦隊 航空戦.
        /// </summary>
        internal static string Title_CombinedFleetAirBattle {
            get {
                return ResourceManager.GetString("Title_CombinedFleetAirBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連合艦隊 長距離空襲戦.
        /// </summary>
        internal static string Title_CombinedFleetAirRaid {
            get {
                return ResourceManager.GetString("Title_CombinedFleetAirRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連合艦隊 開幕夜戦.
        /// </summary>
        internal static string Title_CombinedNightOnly {
            get {
                return ResourceManager.GetString("Title_CombinedNightOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連合艦隊-機動部隊 昼戦.
        /// </summary>
        internal static string Title_CombinedNormalDay {
            get {
                return ResourceManager.GetString("Title_CombinedNormalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常艦隊 対連合艦隊 昼戦.
        /// </summary>
        internal static string Title_EnemyCombinedDay {
            get {
                return ResourceManager.GetString("Title_EnemyCombinedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対連合艦隊 夜戦.
        /// </summary>
        internal static string Title_EnemyCombinedNight {
            get {
                return ResourceManager.GetString("Title_EnemyCombinedNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常艦隊 開幕夜戦.
        /// </summary>
        internal static string Title_NightOnly {
            get {
                return ResourceManager.GetString("Title_NightOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常艦隊 昼戦.
        /// </summary>
        internal static string Title_NormalDay {
            get {
                return ResourceManager.GetString("Title_NormalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常艦隊 航空戦.
        /// </summary>
        internal static string Title_NormalFleetAirBattle {
            get {
                return ResourceManager.GetString("Title_NormalFleetAirBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常艦隊 長距離空襲戦.
        /// </summary>
        internal static string Title_NormalFleetAirRaid {
            get {
                return ResourceManager.GetString("Title_NormalFleetAirRaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通常艦隊 夜戦.
        /// </summary>
        internal static string Title_NormalNight {
            get {
                return ResourceManager.GetString("Title_NormalNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 演習 昼戦.
        /// </summary>
        internal static string Title_PracticeDay {
            get {
                return ResourceManager.GetString("Title_PracticeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 演習 夜戦.
        /// </summary>
        internal static string Title_PracticeNight {
            get {
                return ResourceManager.GetString("Title_PracticeNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷撃+爆撃.
        /// </summary>
        internal static string TorpBombingAttack {
            get {
                return ResourceManager.GetString("TorpBombingAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷撃.
        /// </summary>
        internal static string TorpedoAttack {
            get {
                return ResourceManager.GetString("TorpedoAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (魚雷x2).
        /// </summary>
        internal static string TorpTorp {
            get {
                return ResourceManager.GetString("TorpTorp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸送部隊.
        /// </summary>
        internal static string TransportFleet {
            get {
                return ResourceManager.GetString("TransportFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 三式弾.
        /// </summary>
        internal static string Type3 {
            get {
                return ResourceManager.GetString("Type3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 無傷.
        /// </summary>
        internal static string Unhurt {
            get {
                return ResourceManager.GetString("Unhurt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未選択.
        /// </summary>
        internal static string Unselected {
            get {
                return ResourceManager.GetString("Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 超長.
        /// </summary>
        internal static string VeryLong {
            get {
                return ResourceManager.GetString("VeryLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中将.
        /// </summary>
        internal static string ViceAdmiral {
            get {
                return ResourceManager.GetString("ViceAdmiral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中堅少佐.
        /// </summary>
        internal static string ViceLtCmdr {
            get {
                return ResourceManager.GetString("ViceLtCmdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 週.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 離脱.
        /// </summary>
        internal static string Withdrawn {
            get {
                return ResourceManager.GetString("Withdrawn", resourceCulture);
            }
        }
    }
}
