//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Notifier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotifierRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotifierRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Notifier.NotifierRes", typeof(NotifierRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提督Exp+.
        /// </summary>
        public static string AdmiralExp {
            get {
                return ResourceManager.GetString("AdmiralExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}「{1}」へ補給を行いました。消費: 燃料x{2}, ボーキサイトx{3}.
        /// </summary>
        public static string AirBaseResupplyCost {
            get {
                return ResourceManager.GetString("AirBaseResupplyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泊地修理発動.
        /// </summary>
        public static string AnchorageRepair {
            get {
                return ResourceManager.GetString("AnchorageRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泊地修理の開始から20分が経過しました。.
        /// </summary>
        public static string AnchorageRepairFinished {
            get {
                return ResourceManager.GetString("AnchorageRepairFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基地航空隊の編成により、ボーキ {0} が消費されました。.
        /// </summary>
        public static string BauxiteConsumedByAddingPlaneToAirBase {
            get {
                return ResourceManager.GetString("BauxiteConsumedByAddingPlaneToAirBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 高速修復材x1.
        /// </summary>
        public static string BucketUsed {
            get {
                return ResourceManager.GetString("BucketUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0} 「{1}」に所属する艦娘の疲労が回復しました。.
        /// </summary>
        public static string ConditionText {
            get {
                return ResourceManager.GetString("ConditionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労回復.
        /// </summary>
        public static string ConditionTitle {
            get {
                return ResourceManager.GetString("ConditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠ドック #{0} で「{1}」の建造が完了しました。.
        /// </summary>
        public static string ConstructionText {
            get {
                return ResourceManager.GetString("ConstructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了.
        /// </summary>
        public static string ConstructionTitle {
            get {
                return ResourceManager.GetString("ConstructionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} が大破しています！.
        /// </summary>
        public static string DamagedText {
            get {
                return ResourceManager.GetString("DamagedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ！大破警告！.
        /// </summary>
        public static string DamagedTitle {
            get {
                return ResourceManager.GetString("DamagedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} を廃棄しました。.
        /// </summary>
        public static string EquipmentHasBenScrapped {
            get {
                return ResourceManager.GetString("EquipmentHasBenScrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修理完了予定: .
        /// </summary>
        public static string ETA {
            get {
                return ResourceManager.GetString("ETA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} の補強装備増設改修が完了しました。.
        /// </summary>
        public static string ExpansionSlotOpened {
            get {
                return ResourceManager.GetString("ExpansionSlotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征結果 - .
        /// </summary>
        public static string ExpeditionResult {
            get {
                return ResourceManager.GetString("ExpeditionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0} 「{1}」が遠征「{2}: {3}」から帰投しました。.
        /// </summary>
        public static string ExpeditionText {
            get {
                return ResourceManager.GetString("ExpeditionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征帰投.
        /// </summary>
        public static string ExpeditionTitle {
            get {
                return ResourceManager.GetString("ExpeditionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知システム: 通知音の再生に失敗しました。.
        /// </summary>
        public static string FailedPlaySound {
            get {
                return ResourceManager.GetString("FailedPlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知システム: 通知画像 {0} の読み込みに失敗しました。.
        /// </summary>
        public static string FailedToLoadImage {
            get {
                return ResourceManager.GetString("FailedToLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知システム: 通知音 {0} のロードに失敗しました。.
        /// </summary>
        public static string FailedToLoadSound {
            get {
                return ResourceManager.GetString("FailedToLoadSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}「{1}」が遠征「{2}: {3}」へ出撃しました。.
        /// </summary>
        public static string HasBeenSentToExpedition {
            get {
                return ResourceManager.GetString("HasBeenSentToExpedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{0}「{1}」が「{2}-{3} {4}」へ出撃しました。.
        /// </summary>
        public static string HasSortiedTo {
            get {
                return ResourceManager.GetString("HasSortiedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 獲得資源なし.
        /// </summary>
        public static string NoResourcesGained {
            get {
                return ResourceManager.GetString("NoResourcesGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}は{1}に改造出来ます。.
        /// </summary>
        public static string RemodelText {
            get {
                return ResourceManager.GetString("RemodelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改造可能.
        /// </summary>
        public static string RemodelTitle {
            get {
                return ResourceManager.GetString("RemodelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠ドック #{0} で「{1}」の修復が完了しました。.
        /// </summary>
        public static string RepairText {
            get {
                return ResourceManager.GetString("RepairText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠完了.
        /// </summary>
        public static string RepairTitle {
            get {
                return ResourceManager.GetString("RepairTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘Exp+.
        /// </summary>
        public static string ShipExp {
            get {
                return ResourceManager.GetString("ShipExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} を解体しました。.
        /// </summary>
        public static string ShipHasBeenScrapped {
            get {
                return ResourceManager.GetString("ShipHasBeenScrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} が Lv. {1} になりました。.
        /// </summary>
        public static string ShipLevelUp {
            get {
                return ResourceManager.GetString("ShipLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補給を行いました。消費: .
        /// </summary>
        public static string ShipsResupplied {
            get {
                return ResourceManager.GetString("ShipsResupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Lv. {1} への改装が完了しました。.
        /// </summary>
        public static string ShipSuccessfullyRemodeled {
            get {
                return ResourceManager.GetString("ShipSuccessfullyRemodeled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚓ {0}-{1}-{2}: {3}に出撃します.
        /// </summary>
        public static string SortieingTo {
            get {
                return ResourceManager.GetString("SortieingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠ドック #{0}で {1} ({2}/{3}) の修復を開始しました。(燃料x{4}, 鋼材x{5}, {6}).
        /// </summary>
        public static string StartedRepairingShip {
            get {
                return ResourceManager.GetString("StartedRepairingShip", resourceCulture);
            }
        }
    }
}
