//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Window {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Window.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空カットイン: {0}
        ///カットイン種別: {1} ({2}).
        /// </summary>
        internal static string AACITooltip {
            get {
                return ResourceManager.GetString("AACITooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空カットイン.
        /// </summary>
        internal static string AACutIn {
            get {
                return ResourceManager.GetString("AACutIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空砲火.
        /// </summary>
        internal static string AAPower {
            get {
                return ResourceManager.GetString("AAPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空戦力.
        /// </summary>
        internal static string AirPower {
            get {
                return ResourceManager.GetString("AirPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空権.
        /// </summary>
        internal static string AirSuperiority {
            get {
                return ResourceManager.GetString("AirSuperiority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空.
        /// </summary>
        internal static string AntiAir {
            get {
                return ResourceManager.GetString("AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装甲.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠.
        /// </summary>
        internal static string Arsenal {
            get {
                return ResourceManager.GetString("Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠ドック #{0}で {1}の建造を開始しました。({2}/{3}/{4}/{5}-{6} 秘書艦: {7}).
        /// </summary>
        internal static string ArsenalLog {
            get {
                return ResourceManager.GetString("ArsenalLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確保: {0}\r\n優勢: {1}\r\n均衡: {2}\r\n劣勢: {3}\r\n.
        /// </summary>
        internal static string ASTooltip {
            get {
                return ResourceManager.GetString("ASTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜.
        /// </summary>
        internal static string ASW {
            get {
                return ResourceManager.GetString("ASW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘.
        /// </summary>
        internal static string Battle {
            get {
                return ResourceManager.GetString("Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 触接中.
        /// </summary>
        internal static string Contacting {
            get {
                return ResourceManager.GetString("Contacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリップボードにコピー(&amp;C).
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 与ダメージ.
        /// </summary>
        internal static string DamageDone {
            get {
                return ResourceManager.GetString("DamageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 損害率.
        /// </summary>
        internal static string DamagePct {
            get {
                return ResourceManager.GetString("DamagePct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼戦.
        /// </summary>
        internal static string DayBattle {
            get {
                return ResourceManager.GetString("DayBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠.
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠時間.
        /// </summary>
        internal static string DockTime {
            get {
                return ResourceManager.GetString("DockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交戦形態.
        /// </summary>
        internal static string EncounterType {
            get {
                return ResourceManager.GetString("EncounterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵軍艦隊.
        /// </summary>
        internal static string EnemyFleet {
            get {
                return ResourceManager.GetString("EnemyFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵陣形.
        /// </summary>
        internal static string EnemyFormation {
            get {
                return ResourceManager.GetString("EnemyFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敵索敵.
        /// </summary>
        internal static string EnemyScout {
            get {
                return ResourceManager.GetString("EnemyScout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 随伴艦隊.
        /// </summary>
        internal static string EscortFleet {
            get {
                return ResourceManager.GetString("EscortFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避.
        /// </summary>
        internal static string Evasion {
            get {
                return ResourceManager.GetString("Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全回復まで 約 {0:D2}:{1:D2}.
        /// </summary>
        internal static string FatigueRestoreTime {
            get {
                return ResourceManager.GetString("FatigueRestoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火力.
        /// </summary>
        internal static string Firepower {
            get {
                return ResourceManager.GetString("Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv合計: {0} / 平均: {1:0.00}\r\n{2}艦隊\r\nドラム缶搭載: {3}個 ({4}艦)\r\n大発動艇搭載: {5}個\r\n総積載: 燃 {6} / 弾 {7}\r\n(1戦当たり 燃 {8} / 弾 {9}).
        /// </summary>
        internal static string FleetTooltip {
            get {
                return ResourceManager.GetString("FleetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自軍艦隊.
        /// </summary>
        internal static string FriendlyFleet {
            get {
                return ResourceManager.GetString("FriendlyFleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 味方陣形.
        /// </summary>
        internal static string FriendlyFormation {
            get {
                return ResourceManager.GetString("FriendlyFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 味方索敵.
        /// </summary>
        internal static string FriendlyScout {
            get {
                return ResourceManager.GetString("FriendlyScout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大破しています！.
        /// </summary>
        internal static string IsTaiha {
            get {
                return ResourceManager.GetString("IsTaiha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵.
        /// </summary>
        internal static string LoS {
            get {
                return ResourceManager.GetString("LoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (旧)2-5式: {0}\r\n2-5式(秋): {1}\r\n2-5新秋簡易式: {2}\r\n.
        /// </summary>
        internal static string LoSTooltip {
            get {
                return ResourceManager.GetString("LoSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運.
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜戦.
        /// </summary>
        internal static string NightBattle {
            get {
                return ResourceManager.GetString("NightBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜間触接.
        /// </summary>
        internal static string NightContact {
            get {
                return ResourceManager.GetString("NightContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜間触接中.
        /// </summary>
        internal static string NightContacting {
            get {
                return ResourceManager.GetString("NightContacting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (なし).
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 射程.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あと {0} 回遠征可能.
        /// </summary>
        internal static string RemainingExpeds {
            get {
                return ResourceManager.GetString("RemainingExpeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退避中.
        /// </summary>
        internal static string Retreating {
            get {
                return ResourceManager.GetString("Retreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵.
        /// </summary>
        internal static string Scouting {
            get {
                return ResourceManager.GetString("Scouting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この画面をキャプチャ(&amp;S).
        /// </summary>
        internal static string ScreenCapture {
            get {
                return ResourceManager.GetString("ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 探照灯照射.
        /// </summary>
        internal static string SearchlightUsed {
            get {
                return ResourceManager.GetString("SearchlightUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第2次.
        /// </summary>
        internal static string SecondStage {
            get {
                return ResourceManager.GetString("SecondStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘.
        /// </summary>
        internal static string ShipGirl {
            get {
                return ResourceManager.GetString("ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}\n火力: {2}/{3}\n雷装: {4}/{5}\n対空: {6}/{7}\n装甲: {8}/{9}\n対潜: {10}/{11}\n回避: {12}/{13}\n索敵: {14}/{15}\n運: {16}\n射程: {17} / 速力: {18}\n(右クリックで図鑑)\n.
        /// </summary>
        internal static string ShipTooltip {
            get {
                return ResourceManager.GetString("ShipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撃墜.
        /// </summary>
        internal static string ShotDown {
            get {
                return ResourceManager.GetString("ShotDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速力.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第1次: -{0}/{1}\r\n第2次: -{2}/{3}\r\n.
        /// </summary>
        internal static string Stage2AATooltip {
            get {
                return ResourceManager.GetString("Stage2AATooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}触接中\r\n第1次: {1}\r\n第2次: {2}.
        /// </summary>
        internal static string Stage2ContactTooltip {
            get {
                return ResourceManager.GetString("Stage2ContactTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}次: {1}\r\nカットイン種別: {2} ({3})\r\n.
        /// </summary>
        internal static string StageXAACI {
            get {
                return ResourceManager.GetString("StageXAACI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第{0}次: (発動せず)\r\n.
        /// </summary>
        internal static string StageXAACIFail {
            get {
                return ResourceManager.GetString("StageXAACIFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 照明弾投射.
        /// </summary>
        internal static string StarShellUsed {
            get {
                return ResourceManager.GetString("StarShellUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了日時.
        /// </summary>
        internal static string TimeToCompletion {
            get {
                return ResourceManager.GetString("TimeToCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv150まで: {0}.
        /// </summary>
        internal static string To150 {
            get {
                return ResourceManager.GetString("To150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv99まで: {0}.
        /// </summary>
        internal static string To99 {
            get {
                return ResourceManager.GetString("To99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大破まで: {0}.
        /// </summary>
        internal static string ToHeavy {
            get {
                return ResourceManager.GetString("ToHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中破まで: {0} / 大破まで: {1}\n.
        /// </summary>
        internal static string ToMidAndHeavy {
            get {
                return ResourceManager.GetString("ToMidAndHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次のレベルまで: {0}.
        /// </summary>
        internal static string ToNextLevel {
            get {
                return ResourceManager.GetString("ToNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改装まで: {0}.
        /// </summary>
        internal static string ToRemodel {
            get {
                return ResourceManager.GetString("ToRemodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷装.
        /// </summary>
        internal static string Torpedo {
            get {
                return ResourceManager.GetString("Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵能力.
        /// </summary>
        internal static string TotalLoS {
            get {
                return ResourceManager.GetString("TotalLoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウキャプチャの確認.
        /// </summary>
        internal static string WCWarningTitle {
            get {
                return ResourceManager.GetString("WCWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウキャプチャ.
        /// </summary>
        internal static string WindowCapture {
            get {
                return ResourceManager.GetString("WindowCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取り込みたいウィンドウへボタンをドラッグ＆ドロップしてください。.
        /// </summary>
        internal static string WindowCaptureInst {
            get {
                return ResourceManager.GetString("WindowCaptureInst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このウィンドウをキャプチャします。よろしいですか？
        ///
        ///注意: ウィンドウによっては正常に取り込めず、不安定になる可能性があります。
        ///データを保存する・母港に戻るなど、安全を確保してから実行してください。
        ///.
        /// </summary>
        internal static string WindowCaptureWarning {
            get {
                return ResourceManager.GetString("WindowCaptureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦績判定.
        /// </summary>
        internal static string WinRank {
            get {
                return ResourceManager.GetString("WinRank", resourceCulture);
            }
        }
    }
}
