//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Window {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GeneralRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Window.GeneralRes", typeof(GeneralRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空戦力.
        /// </summary>
        internal static string AirPower {
            get {
                return ResourceManager.GetString("AirPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空.
        /// </summary>
        internal static string AntiAir {
            get {
                return ResourceManager.GetString("AntiAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装甲.
        /// </summary>
        internal static string Armor {
            get {
                return ResourceManager.GetString("Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠.
        /// </summary>
        internal static string Arsenal {
            get {
                return ResourceManager.GetString("Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠ドック #{0}で {1}の建造を開始しました。({2}/{3}/{4}/{5}-{6} 秘書艦: {7}).
        /// </summary>
        internal static string ArsenalLog {
            get {
                return ResourceManager.GetString("ArsenalLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確保: {0}\r\n優勢: {1}\r\n均衡: {2}\r\n劣勢: {3}\r\n.
        /// </summary>
        internal static string ASTooltip {
            get {
                return ResourceManager.GetString("ASTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜.
        /// </summary>
        internal static string ASW {
            get {
                return ResourceManager.GetString("ASW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クリップボードにコピー(&amp;C).
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 昼戦.
        /// </summary>
        internal static string DayBattle {
            get {
                return ResourceManager.GetString("DayBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠.
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠時間.
        /// </summary>
        internal static string DockTime {
            get {
                return ResourceManager.GetString("DockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避.
        /// </summary>
        internal static string Evasion {
            get {
                return ResourceManager.GetString("Evasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全回復まで 約 {0:D2}:{1:D2}.
        /// </summary>
        internal static string FatigueRestoreTime {
            get {
                return ResourceManager.GetString("FatigueRestoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火力.
        /// </summary>
        internal static string Firepower {
            get {
                return ResourceManager.GetString("Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv合計: {0} / 平均: {1:0.00}\r\n{2}艦隊\r\nドラム缶搭載: {3}個 ({4}艦)\r\n大発動艇搭載: {5}個\r\n総積載: 燃 {6} / 弾 {7}\r\n(1戦当たり 燃 {8} / 弾 {9}).
        /// </summary>
        internal static string FleetTooltip {
            get {
                return ResourceManager.GetString("FleetTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大破しています！.
        /// </summary>
        internal static string IsTaiha {
            get {
                return ResourceManager.GetString("IsTaiha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵.
        /// </summary>
        internal static string LoS {
            get {
                return ResourceManager.GetString("LoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (旧)2-5式: {0}\r\n2-5式(秋): {1}\r\n2-5新秋簡易式: {2}\r\n.
        /// </summary>
        internal static string LoSTooltip {
            get {
                return ResourceManager.GetString("LoSTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 運.
        /// </summary>
        internal static string Luck {
            get {
                return ResourceManager.GetString("Luck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜戦.
        /// </summary>
        internal static string NightBattle {
            get {
                return ResourceManager.GetString("NightBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 射程.
        /// </summary>
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あと {0} 回遠征可能.
        /// </summary>
        internal static string RemainingExpeds {
            get {
                return ResourceManager.GetString("RemainingExpeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退避中.
        /// </summary>
        internal static string Retreating {
            get {
                return ResourceManager.GetString("Retreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to この画面をキャプチャ(&amp;S).
        /// </summary>
        internal static string ScreenCapture {
            get {
                return ResourceManager.GetString("ScreenCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦娘.
        /// </summary>
        internal static string ShipGirl {
            get {
                return ResourceManager.GetString("ShipGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}\n火力: {2}/{3}\n雷装: {4}/{5}\n対空: {6}/{7}\n装甲: {8}/{9}\n対潜: {10}/{11}\n回避: {12}/{13}\n索敵: {14}/{15}\n運: {16}\n射程: {17} / 速力: {18}\n(右クリックで図鑑)\n.
        /// </summary>
        internal static string ShipTooltip {
            get {
                return ResourceManager.GetString("ShipTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 速力.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了日時.
        /// </summary>
        internal static string TimeToCompletion {
            get {
                return ResourceManager.GetString("TimeToCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv150まで: {0}.
        /// </summary>
        internal static string To150 {
            get {
                return ResourceManager.GetString("To150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lv99まで: {0}.
        /// </summary>
        internal static string To99 {
            get {
                return ResourceManager.GetString("To99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大破まで: {0}.
        /// </summary>
        internal static string ToHeavy {
            get {
                return ResourceManager.GetString("ToHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中破まで: {0} / 大破まで: {1}\n.
        /// </summary>
        internal static string ToMidAndHeavy {
            get {
                return ResourceManager.GetString("ToMidAndHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次のレベルまで: {0}.
        /// </summary>
        internal static string ToNextLevel {
            get {
                return ResourceManager.GetString("ToNextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改装まで: {0}.
        /// </summary>
        internal static string ToRemodel {
            get {
                return ResourceManager.GetString("ToRemodel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷装.
        /// </summary>
        internal static string Torpedo {
            get {
                return ResourceManager.GetString("Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵能力.
        /// </summary>
        internal static string TotalLoS {
            get {
                return ResourceManager.GetString("TotalLoS", resourceCulture);
            }
        }
    }
}
