//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Window {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Window.Menus", typeof(Menus).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下(&amp;B).
        /// </summary>
        internal static string Alignment_Bottom {
            get {
                return ResourceManager.GetString("Alignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非表示(&amp;I).
        /// </summary>
        internal static string Alignment_Invisible {
            get {
                return ResourceManager.GetString("Alignment_Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左(&amp;L).
        /// </summary>
        internal static string Alignment_Left {
            get {
                return ResourceManager.GetString("Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右(&amp;R).
        /// </summary>
        internal static string Alignment_Right {
            get {
                return ResourceManager.GetString("Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上(&amp;T).
        /// </summary>
        internal static string Alignment_Top {
            get {
                return ResourceManager.GetString("Alignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠(&amp;A).
        /// </summary>
        internal static string Arsenal {
            get {
                return ResourceManager.GetString("Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘(&amp;B).
        /// </summary>
        internal static string Battle {
            get {
                return ResourceManager.GetString("Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザ.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造記録(&amp;R).
        /// </summary>
        internal static string BuildRecord {
            get {
                return ResourceManager.GetString("BuildRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了(&amp;X).
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 羅針盤(&amp;C).
        /// </summary>
        internal static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コントロールウィンドウ(&amp;C).
        /// </summary>
        internal static string ControlWindow {
            get {
                return ResourceManager.GetString("ControlWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバッグ(&amp;D).
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 古いAPIデータを削除(&amp;D).
        /// </summary>
        internal static string DeleteOldAPI {
            get {
                return ResourceManager.GetString("DeleteOldAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全てのウィンドウを開放(&amp;R).
        /// </summary>
        internal static string DetachAll {
            get {
                return ResourceManager.GetString("DetachAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開発記録(&amp;V).
        /// </summary>
        internal static string DevRecord {
            get {
                return ResourceManager.GetString("DevRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠(&amp;D).
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドロップ記録(&amp;D).
        /// </summary>
        internal static string DropRecord {
            get {
                return ResourceManager.GetString("DropRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備図鑑(&amp;E).
        /// </summary>
        internal static string EquipEncyclopedia {
            get {
                return ResourceManager.GetString("EquipEncyclopedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備一覧(&amp;Q).
        /// </summary>
        internal static string EquipmentList {
            get {
                return ResourceManager.GetString("EquipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル(&amp;F).
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊一覧(&amp;O).
        /// </summary>
        internal static string FleetList {
            get {
                return ResourceManager.GetString("FleetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊(&amp;F).
        /// </summary>
        internal static string Fleets {
            get {
                return ResourceManager.GetString("Fleets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 司令部(&amp;H).
        /// </summary>
        internal static string Headquarters {
            get {
                return ResourceManager.GetString("Headquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ(&amp;H).
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報(&amp;I).
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト(&amp;L).
        /// </summary>
        internal static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 別のファイルからロード(&amp;O)....
        /// </summary>
        internal static string LayoutOpen {
            get {
                return ResourceManager.GetString("LayoutOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロード(&amp;L).
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルからAPIをロード(&amp;L)....
        /// </summary>
        internal static string LoadAPIFromFile {
            get {
                return ResourceManager.GetString("LoadAPIFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIリストをロード(&amp;I)....
        /// </summary>
        internal static string LoadAPIList {
            get {
                return ResourceManager.GetString("LoadAPIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧 api_start2 からレコードを構築(&amp;O)....
        /// </summary>
        internal static string LoadOldAPIRecord {
            get {
                return ResourceManager.GetString("LoadOldAPIRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ(&amp;L).
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オンラインヘルプ(&amp;H)....
        /// </summary>
        internal static string OnlineHelp {
            get {
                return ResourceManager.GetString("OnlineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置(&amp;A).
        /// </summary>
        internal static string Other_Alignment {
            get {
                return ResourceManager.GetString("Other_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタイルシートを適用する.
        /// </summary>
        internal static string Other_ApplyStyleSheet {
            get {
                return ResourceManager.GetString("Other_ApplyStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュのクリア(&amp;C).
        /// </summary>
        internal static string Other_ClearCache {
            get {
                return ResourceManager.GetString("Other_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミュート(&amp;M).
        /// </summary>
        internal static string Other_Mute {
            get {
                return ResourceManager.GetString("Other_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移動(&amp;N)....
        /// </summary>
        internal static string Other_Navigate {
            get {
                return ResourceManager.GetString("Other_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインページへ移動(&amp;L).
        /// </summary>
        internal static string Other_NavigateToLogInPage {
            get {
                return ResourceManager.GetString("Other_NavigateToLogInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新(&amp;R).
        /// </summary>
        internal static string Other_Refresh {
            get {
                return ResourceManager.GetString("Other_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地域制限クッキーを設定.
        /// </summary>
        internal static string Other_RegionCookie {
            get {
                return ResourceManager.GetString("Other_RegionCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショット(&amp;S).
        /// </summary>
        internal static string Other_Screenshot {
            get {
                return ResourceManager.GetString("Other_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム(&amp;Z).
        /// </summary>
        internal static string Other_Zoom {
            get {
                return ResourceManager.GetString("Other_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在%.
        /// </summary>
        internal static string Other_Zoom_Current {
            get {
                return ResourceManager.GetString("Other_Zoom_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴったり.
        /// </summary>
        internal static string Other_Zoom_Fit {
            get {
                return ResourceManager.GetString("Other_Zoom_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務(&amp;Q).
        /// </summary>
        internal static string Quest {
            get {
                return ResourceManager.GetString("Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て再検索して取り込む(&amp;S).
        /// </summary>
        internal static string ReattachAll {
            get {
                return ResourceManager.GetString("ReattachAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコード(&amp;R).
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船リソースをリネーム(&amp;R)....
        /// </summary>
        internal static string RenameShipResource {
            get {
                return ResourceManager.GetString("RenameShipResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資源チャート(&amp;C).
        /// </summary>
        internal static string ResourceChart {
            get {
                return ResourceManager.GetString("ResourceChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブ(&amp;S).
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定(&amp;C)....
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船図鑑(&amp;S).
        /// </summary>
        internal static string ShipEncyclopedia {
            get {
                return ResourceManager.GetString("ShipEncyclopedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船グループ(&amp;G).
        /// </summary>
        internal static string ShipGroup {
            get {
                return ResourceManager.GetString("ShipGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦名を表示(&amp;V).
        /// </summary>
        internal static string ShowShipName {
            get {
                return ResourceManager.GetString("ShowShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツールメニューを表示.
        /// </summary>
        internal static string ShowToolMenu {
            get {
                return ResourceManager.GetString("ShowToolMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試製七四式電子観測儀.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール(&amp;T).
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン情報(&amp;V).
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示(&amp;V).
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウキャプチャ(&amp;W).
        /// </summary>
        internal static string WindowCapture {
            get {
                return ResourceManager.GetString("WindowCapture", resourceCulture);
            }
        }
    }
}
