namespace ElectronicObserver.Core.Types.Extensions;
public static class EquipmentIconTypeExtensions
{
	public static string TranslatedName(this EquipmentIconType type) => type switch
	{
		EquipmentIconType.Nothing => Properties.EquipmentIconType.Nothing,
		EquipmentIconType.MainGunSmall => Properties.EquipmentIconType.MainGunSmall,
		EquipmentIconType.MainGunMedium => Properties.EquipmentIconType.MainGunMedium,
		EquipmentIconType.MainGunLarge => Properties.EquipmentIconType.MainGunLarge,
		EquipmentIconType.SecondaryGun => Properties.EquipmentIconType.SecondaryGun,
		EquipmentIconType.Torpedo => Properties.EquipmentIconType.Torpedo,
		EquipmentIconType.CarrierBasedFighter => Properties.EquipmentIconType.CarrierBasedFighter,
		EquipmentIconType.CarrierBasedBomber => Properties.EquipmentIconType.CarrierBasedBomber,
		EquipmentIconType.CarrierBasedTorpedo => Properties.EquipmentIconType.CarrierBasedTorpedo,
		EquipmentIconType.CarrierBasedRecon => Properties.EquipmentIconType.CarrierBasedRecon,
		EquipmentIconType.Seaplane => Properties.EquipmentIconType.Seaplane,
		EquipmentIconType.Radar => Properties.EquipmentIconType.Radar,
		EquipmentIconType.AAShell => Properties.EquipmentIconType.AAShell,
		EquipmentIconType.APShell => Properties.EquipmentIconType.APShell,
		EquipmentIconType.DamageControl => Properties.EquipmentIconType.DamageControl,
		EquipmentIconType.AAGun => Properties.EquipmentIconType.AAGun,
		EquipmentIconType.HighAngleGun => Properties.EquipmentIconType.HighAngleGun,
		EquipmentIconType.DepthCharge => Properties.EquipmentIconType.DepthCharge,
		EquipmentIconType.Sonar => Properties.EquipmentIconType.Sonar,
		EquipmentIconType.Engine => Properties.EquipmentIconType.Engine,
		EquipmentIconType.LandingCraft => Properties.EquipmentIconType.LandingCraft,
		EquipmentIconType.Autogyro => Properties.EquipmentIconType.Autogyro,
		EquipmentIconType.ASPatrol => Properties.EquipmentIconType.ASPatrol,
		EquipmentIconType.ExtraArmor => Properties.EquipmentIconType.ExtraArmor,
		EquipmentIconType.Searchlight => Properties.EquipmentIconType.Searchlight,
		EquipmentIconType.TransportContainer => Properties.EquipmentIconType.TransportContainer,
		EquipmentIconType.RepairFacility => Properties.EquipmentIconType.RepairFacility,
		EquipmentIconType.StarShell => Properties.EquipmentIconType.StarShell,
		EquipmentIconType.CommandFacility => Properties.EquipmentIconType.CommandFacility,
		EquipmentIconType.AviationPersonnel => Properties.EquipmentIconType.AviationPersonnel,
		EquipmentIconType.AADirector => Properties.EquipmentIconType.AADirector,
		EquipmentIconType.Rocket => Properties.EquipmentIconType.Rocket,
		EquipmentIconType.SurfaceShipPersonnel => Properties.EquipmentIconType.SurfaceShipPersonnel,
		EquipmentIconType.FlyingBoat => Properties.EquipmentIconType.FlyingBoat,
		EquipmentIconType.Ration => Properties.EquipmentIconType.Ration,
		EquipmentIconType.Supplies => Properties.EquipmentIconType.Supplies,
		EquipmentIconType.SpecialAmphibiousTank => Properties.EquipmentIconType.SpecialAmphibiousTank,
		EquipmentIconType.LandBasedAttacker => Properties.EquipmentIconType.LandBasedAttacker,
		EquipmentIconType.Interceptor => Properties.EquipmentIconType.Interceptor,
		EquipmentIconType.JetBomberKeiun => Properties.EquipmentIconType.JetBomberKeiun,
		EquipmentIconType.JetBomberKikka => Properties.EquipmentIconType.JetBomberKikka,
		EquipmentIconType.TransportMaterial => Properties.EquipmentIconType.TransportMaterial,
		EquipmentIconType.SubmarineEquipment => Properties.EquipmentIconType.SubmarineEquipment,
		EquipmentIconType.SeaplaneFighter => Properties.EquipmentIconType.SeaplaneFighter,
		EquipmentIconType.LandBasedFighter => Properties.EquipmentIconType.LandBasedFighter,
		EquipmentIconType.NightFighter => Properties.EquipmentIconType.NightFighter,
		EquipmentIconType.NightAttacker => Properties.EquipmentIconType.NightAttacker,
		EquipmentIconType.LandBasedASPatrol => Properties.EquipmentIconType.LandBasedASPatrol,
		EquipmentIconType.LandAssaulter => Properties.EquipmentIconType.LandAssaulter,
		EquipmentIconType.HeavyBomber => Properties.EquipmentIconType.HeavyBomber,
		EquipmentIconType.NightSeaplane => Properties.EquipmentIconType.NightSeaplane,
		EquipmentIconType.NightSeaplaneBomber => Properties.EquipmentIconType.NightSeaplaneBomber,
		EquipmentIconType.ArmyInfantry => Properties.EquipmentIconType.ArmyInfantry,
		EquipmentIconType.SmokeGenerator => Properties.EquipmentIconType.SmokeGenerator,
		EquipmentIconType.BarrageBalloon => Properties.EquipmentIconType.BarrageBalloon,
		EquipmentIconType.LandBasedFighterJet => Properties.EquipmentIconType.LandBasedFighterJet,
		EquipmentIconType.LandBasedFighterShinden => Properties.EquipmentIconType.LandBasedFighter,
		EquipmentIconType.Locked => Properties.EquipmentIconType.Locked,
		_ => Properties.EquipmentIconType.Unknown,
	};
}
