//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties.Utility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SoftwareInformation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SoftwareInformation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.Utility.SoftwareInformation", typeof(SoftwareInformation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 七四式を閉じて、アップデート処理を完了します。自動的に再起動されます。.
        /// </summary>
        public static string CloseElectronicObserverToCompleteTheUpdate {
            get {
                return ResourceManager.GetString("CloseElectronicObserverToCompleteTheUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ダウンロード終了。.
        /// </summary>
        public static string DownloadFinished {
            get {
                return ResourceManager.GetString("DownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデートをダウンロード中....
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 七四式のダウンロードに失敗しました。.
        /// </summary>
        public static string FailedToDownloadElectronicObserver {
            get {
                return ResourceManager.GetString("FailedToDownloadElectronicObserver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデータのダウンロードに失敗しました。.
        /// </summary>
        public static string FailedToDownloadUpdater {
            get {
                return ResourceManager.GetString("FailedToDownloadUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデート情報の取得に失敗しました。.
        /// </summary>
        public static string FailedToObtainUpdateData {
            get {
                return ResourceManager.GetString("FailedToObtainUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新データの解析に失敗しました：.
        /// </summary>
        public static string FailedToParseUpdateData {
            get {
                return ResourceManager.GetString("FailedToParseUpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}データの更新に失敗しました。{1}.
        /// </summary>
        public static string FailedToUpdateFile {
            get {
                return ResourceManager.GetString("FailedToUpdateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル{0}が更新されました。.
        /// </summary>
        public static string FileUpdated {
            get {
                return ResourceManager.GetString("FileUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデート情報の取得に失敗しました。.
        /// </summary>
        public static string InvalidUpdateUrl {
            get {
                return ResourceManager.GetString("InvalidUpdateUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデートのダウンロードを開始しました。{0}.
        /// </summary>
        public static string StartedDownloadingUpdate {
            get {
                return ResourceManager.GetString("StartedDownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻訳ファイルを更新しました。.
        /// </summary>
        public static string TranslationFilesUpdated {
            get {
                return ResourceManager.GetString("TranslationFilesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデータのダウンロードが終了しました。.
        /// </summary>
        public static string UpdaterDownloadFinished {
            get {
                return ResourceManager.GetString("UpdaterDownloadFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to お使いのバージョンは最新です。.
        /// </summary>
        public static string YouAreUsingTheLatestVersion {
            get {
                return ResourceManager.GetString("YouAreUsingTheLatestVersion", resourceCulture);
            }
        }
    }
}
