//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Window.Dialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Window.Dialog.ConfigRes", typeof(ConfigRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アクセスキー：.
        /// </summary>
        internal static string AccessKey {
            get {
                return ResourceManager.GetString("AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン名をファイルに追加します。.
        /// </summary>
        internal static string AddVersionToFile {
            get {
                return ResourceManager.GetString("AddVersionToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空戦力計算式：.
        /// </summary>
        internal static string AirSuperiorityMethod {
            get {
                return ResourceManager.GetString("AirSuperiorityMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー音を鳴らす.
        /// </summary>
        internal static string AlertOnError {
            get {
                return ResourceManager.GetString("AlertOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ソート順を変更可能にする.
        /// </summary>
        internal static string AllowUserToSortRows {
            get {
                return ResourceManager.GetString("AllowUserToSortRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泊地修理.
        /// </summary>
        internal static string AnchorageRepairFinish {
            get {
                return ResourceManager.GetString("AnchorageRepairFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適用.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在のテキストボックスの内容を適用します。.
        /// </summary>
        internal static string ApplyEffectsOfBox {
            get {
                return ResourceManager.GetString("ApplyEffectsOfBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリに登録します。よろしいですか？
        ///＊完全に適用するには再起動が必要です。.
        /// </summary>
        internal static string ApplyingRegistry {
            get {
                return ResourceManager.GetString("ApplyingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＊各ダイアログでOKを押した時点で適用されます.
        /// </summary>
        internal static string ApplyonOK {
            get {
                return ResourceManager.GetString("ApplyonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 適用.
        /// </summary>
        internal static string ApplyRegistry {
            get {
                return ResourceManager.GetString("ApplyRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリに対して設定を適用します。
        ///下の[OK]ボタンでは反映されないのでご注意ください。.
        /// </summary>
        internal static string ApplyRegistryHint {
            get {
                return ResourceManager.GetString("ApplyRegistryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタイルシートを適用する.
        /// </summary>
        internal static string ApplyStyleSheet {
            get {
                return ResourceManager.GetString("ApplyStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これ画面のみを表示できるようにします。
        ///環境によっては表示が乱れます、その場合は無効にしてください。.
        /// </summary>
        internal static string ApplyStyleSheetHint {
            get {
                return ResourceManager.GetString("ApplyStyleSheetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠.
        /// </summary>
        internal static string Arsenal {
            get {
                return ResourceManager.GetString("Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動更新する.
        /// </summary>
        internal static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船データを自動更新するかを指定します。.
        /// </summary>
        internal static string AutoUpdateHint {
            get {
                return ResourceManager.GetString("AutoUpdateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-5式(秋).
        /// </summary>
        internal static string Autumn25 {
            get {
                return ResourceManager.GetString("Autumn25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 動作.
        /// </summary>
        internal static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGMプレイヤーを有効にする.
        /// </summary>
        internal static string BGMPlayer_Enabled {
            get {
                return ResourceManager.GetString("BGMPlayer_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在の場面に合わせてお好みのBGMを再生する機能です。.
        /// </summary>
        internal static string BGMPlayer_Enabled_Tooltip {
            get {
                return ResourceManager.GetString("BGMPlayer_Enabled_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音楽ファイルを開く.
        /// </summary>
        internal static string BGMPlayer_OpenMusicFile {
            get {
                return ResourceManager.GetString("BGMPlayer_OpenMusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGMの設定.
        /// </summary>
        internal static string BGMPlayer_Settings {
            get {
                return ResourceManager.GetString("BGMPlayer_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音量一括適用.
        /// </summary>
        internal static string BGMPlayer_SetVolumeAll {
            get {
                return ResourceManager.GetString("BGMPlayer_SetVolumeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミュートを同期.
        /// </summary>
        internal static string BGMPlayer_SyncBrowserMute {
            get {
                return ResourceManager.GetString("BGMPlayer_SyncBrowserMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザのミュートと連動させるかを指定します。.
        /// </summary>
        internal static string BGMPlayer_SyncBrowserMute_Tooltip {
            get {
                return ResourceManager.GetString("BGMPlayer_SyncBrowserMute_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完了時に点滅させる.
        /// </summary>
        internal static string BlinkAtCompletion {
            get {
                return ResourceManager.GetString("BlinkAtCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船/装備が満タンの時点滅する.
        /// </summary>
        internal static string BlinkAtMaximum {
            get {
                return ResourceManager.GetString("BlinkAtMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザ.
        /// </summary>
        internal static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザ2.
        /// </summary>
        internal static string Browser2 {
            get {
                return ResourceManager.GetString("Browser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザバージョン：.
        /// </summary>
        internal static string BrowserVersion {
            get {
                return ResourceManager.GetString("BrowserVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内蔵ブラウザのバージョンを指定します。
        ///7000がIE7相当、8000がIE8相当、11000がIE11相当です。
        ///バージョンによって動作が変わる可能性があります。.
        /// </summary>
        internal static string BrowserVersionHint {
            get {
                return ResourceManager.GetString("BrowserVersionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャンセル.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一度に表示する候補数：.
        /// </summary>
        internal static string CandidateDisplayCount {
            get {
                return ResourceManager.GetString("CandidateDisplayCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリを削除します。よろしいですか？
        ///＊完全に適用するには再起動が必要です。.
        /// </summary>
        internal static string ClearingRegistry {
            get {
                return ResourceManager.GetString("ClearingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通信.
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一度に表示する候補数：.
        /// </summary>
        internal static string CompassCandidate {
            get {
                return ResourceManager.GetString("CompassCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効な場合再読み込みするときに確認ダイアログを表示します。
        ///誤爆防止にご利用ください。.
        /// </summary>
        internal static string ConfirmRefreshHint {
            get {
                return ResourceManager.GetString("ConfirmRefreshHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート番号を設定します。.
        /// </summary>
        internal static string ConnectionPort {
            get {
                return ResourceManager.GetString("ConnectionPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造完了.
        /// </summary>
        internal static string ConstructEnd {
            get {
                return ResourceManager.GetString("ConstructEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＊無闇に変更すると設定・レコードが読めなくなる可能性があります.
        /// </summary>
        internal static string CorruptLogs {
            get {
                return ResourceManager.GetString("CorruptLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作成完了.
        /// </summary>
        internal static string CreationComplete {
            get {
                return ResourceManager.GetString("CreationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デイリー.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to データベース.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「艦これ統計データベース」へデータを送信できます。\r\n詳細やアクセスキーの取得は以下のサイトを参照してください。(外部ブラウザが開きます).
        /// </summary>
        internal static string DatabaseDescription {
            get {
                return ResourceManager.GetString("DatabaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバッグ.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 削除.
        /// </summary>
        internal static string DeleteRegistry {
            get {
                return ResourceManager.GetString("DeleteRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリを削除します。.
        /// </summary>
        internal static string DeleteRegistryHint {
            get {
                return ResourceManager.GetString("DeleteRegistryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修レベル・熟練度を表示する.
        /// </summary>
        internal static string DisplayEquipLevels {
            get {
                return ResourceManager.GetString("DisplayEquipLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備の改修レベルと艦載機熟練度を表示するかを指定します。
        ///.
        /// </summary>
        internal static string DisplayEquipLevelsTooltip {
            get {
                return ResourceManager.GetString("DisplayEquipLevelsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠.
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠完了.
        /// </summary>
        internal static string DockEnd {
            get {
                return ResourceManager.GetString("DockEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起動時に読み込む.
        /// </summary>
        internal static string EnableBrowser {
            get {
                return ResourceManager.GetString("EnableBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入出力するファイルのエンコーディングを指定します。
        ///＊注意＊変更すると今までの設定やレコードが読み込めなくなる可能性があります。
        ///十分注意して変更してください。.
        /// </summary>
        internal static string EncodingHint {
            get {
                return ResourceManager.GetString("EncodingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文字コード.
        /// </summary>
        internal static string Enocding {
            get {
                return ResourceManager.GetString("Enocding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 両方表示.
        /// </summary>
        internal static string EquipmentLevelVisibility_Both {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非表示.
        /// </summary>
        internal static string EquipmentLevelVisibility_Hidden {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修レベルのみ.
        /// </summary>
        internal static string EquipmentLevelVisibility_ImprovOnly {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ImprovOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 改修レベル優先.
        /// </summary>
        internal static string EquipmentLevelVisibility_ImprovPrio {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ImprovPrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦載機熟練度のみ.
        /// </summary>
        internal static string EquipmentLevelVisibility_ProfOnly {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ProfOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦載機熟練度優先.
        /// </summary>
        internal static string EquipmentLevelVisibility_ProfPrio {
            get {
                return ResourceManager.GetString("EquipmentLevelVisibility_ProfPrio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征帰投.
        /// </summary>
        internal static string ExpedReturn {
            get {
                return ResourceManager.GetString("ExpedReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリの削除に失敗しました。.
        /// </summary>
        internal static string FailedClearRegistry {
            get {
                return ResourceManager.GetString("FailedClearRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリからの読み込みに失敗しました。.
        /// </summary>
        internal static string FailedLoadRegistry {
            get {
                return ResourceManager.GetString("FailedLoadRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動プロキシ設定スクリプトの保存に失敗しました。.
        /// </summary>
        internal static string FailedSaveProxy {
            get {
                return ResourceManager.GetString("FailedSaveProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリへの書き込みに失敗しました。.
        /// </summary>
        internal static string FailedSaveRegistry {
            get {
                return ResourceManager.GetString("FailedSaveRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザバージョンをレジストリに書き込めませんでした。.
        /// </summary>
        internal static string FailWriteRegistry {
            get {
                return ResourceManager.GetString("FailWriteRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労回復.
        /// </summary>
        internal static string FatigueRestore {
            get {
                return ResourceManager.GetString("FatigueRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル名.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルタ.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有効な場合、画面に合わせて自動的に拡大・縮小します。.
        /// </summary>
        internal static string FitHint {
            get {
                return ResourceManager.GetString("FitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦名表示部の幅を固定し、スペースを節約します。
        ///代わりに長い名前を持つ艦娘は見切れます。.
        /// </summary>
        internal static string FixWidthHint {
            get {
                return ResourceManager.GetString("FixWidthHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashのモードを指定します。
        ///既定値は opaque です。
        ///direct にするとパフォーマンスが向上する可能性があります。.
        /// </summary>
        internal static string FlashModeHint {
            get {
                return ResourceManager.GetString("FlashModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash品質設定.
        /// </summary>
        internal static string FlashQuality {
            get {
                return ResourceManager.GetString("FlashQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to タイマー完了時に点滅させる.
        /// </summary>
        internal static string FleetBlinkAtCompletion {
            get {
                return ResourceManager.GetString("FleetBlinkAtCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フォルダの参照.
        /// </summary>
        internal static string FolderSearch {
            get {
                return ResourceManager.GetString("FolderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 判定式(33).
        /// </summary>
        internal static string Formula33 {
            get {
                return ResourceManager.GetString("Formula33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPUレンダリング.
        /// </summary>
        internal static string GPURendering {
            get {
                return ResourceManager.GetString("GPURendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内蔵ブラウザでGPUレンダリングを使用するかを指定します。\r\n環境によっては処理が高速化します。.
        /// </summary>
        internal static string GPURenderingHint {
            get {
                return ResourceManager.GetString("GPURenderingHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to グループ.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (非表示です。デバッグメニューを有効にしてください。).
        /// </summary>
        internal static string HiddenJSON {
            get {
                return ResourceManager.GetString("HiddenJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動更新する.
        /// </summary>
        internal static string Json_AutoUpdate {
            get {
                return ResourceManager.GetString("Json_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API の送受信時に、自動で表示を更新するかを指定します。\r\n多少重くなる可能性があります。\r\n.
        /// </summary>
        internal static string Json_AutoUpdateHint {
            get {
                return ResourceManager.GetString("Json_AutoUpdateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウトファイル.
        /// </summary>
        internal static string LayoutFile {
            get {
                return ResourceManager.GetString("LayoutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト ファイルを開く.
        /// </summary>
        internal static string LayoutSearch {
            get {
                return ResourceManager.GetString("LayoutSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 先頭：.
        /// </summary>
        internal static string Lead {
            get {
                return ResourceManager.GetString("Lead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロック中でもフロートウィンドウを閉じる.
        /// </summary>
        internal static string Life_CanCloseFloatWindowInLock {
            get {
                return ResourceManager.GetString("Life_CanCloseFloatWindowInLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウトをロックする.
        /// </summary>
        internal static string Life_LockLayout {
            get {
                return ResourceManager.GetString("Life_LockLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サイズやレイアウトの変更を防止するかを指定します。.
        /// </summary>
        internal static string Life_LockLayout_Tooltip {
            get {
                return ResourceManager.GetString("Life_LockLayout_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘ログを保存する.
        /// </summary>
        internal static string Log_SaveBattleLog {
            get {
                return ResourceManager.GetString("Log_SaveBattleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコードの自動保存：.
        /// </summary>
        internal static string LoggingInterval {
            get {
                return ResourceManager.GetString("LoggingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログの出力レベル.
        /// </summary>
        internal static string LoggingLevel {
            get {
                return ResourceManager.GetString("LoggingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインURL.
        /// </summary>
        internal static string LoginURL {
            get {
                return ResourceManager.GetString("LoginURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ループ.
        /// </summary>
        internal static string Loop {
            get {
                return ResourceManager.GetString("Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 索敵能力計算式.
        /// </summary>
        internal static string LosFormula {
            get {
                return ResourceManager.GetString("LosFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メインフォント.
        /// </summary>
        internal static string Mainfont {
            get {
                return ResourceManager.GetString("Mainfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＊膨大なサイズになる可能性があります。.
        /// </summary>
        internal static string MayIncreaseSize {
            get {
                return ResourceManager.GetString("MayIncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to モード.
        /// </summary>
        internal static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to マンスリー.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 疲労度ボーダー.
        /// </summary>
        internal static string MoraleBorder {
            get {
                return ResourceManager.GetString("MoraleBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-5新秋簡易式.
        /// </summary>
        internal static string New25 {
            get {
                return ResourceManager.GetString("New25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新判定式(33).
        /// </summary>
        internal static string NewFormula33 {
            get {
                return ResourceManager.GetString("NewFormula33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 「次のレベルまでに必要な経験値」を表示するかを指定します。
        ///省略した場合スペースを節約できます。.
        /// </summary>
        internal static string NextXPHint {
            get {
                return ResourceManager.GetString("NextXPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知の設定....
        /// </summary>
        internal static string NotificationSetting {
            get {
                return ResourceManager.GetString("NotificationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (旧)2-5式.
        /// </summary>
        internal static string Old25 {
            get {
                return ResourceManager.GetString("Old25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 一回限り・その他.
        /// </summary>
        internal static string OneTimeOther {
            get {
                return ResourceManager.GetString("OneTimeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動プロキシ設定スクリプトの出力....
        /// </summary>
        internal static string OutputProxyScript {
            get {
                return ResourceManager.GetString("OutputProxyScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パス：.
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ポート.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 威力表示交戦形態：.
        /// </summary>
        internal static string PowerEngagementForm {
            get {
                return ResourceManager.GetString("PowerEngagementForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務進捗の自動保存：.
        /// </summary>
        internal static string ProgressAutoSaving {
            get {
                return ResourceManager.GetString("ProgressAutoSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1日ごと.
        /// </summary>
        internal static string ProgressAutoSaving_Daily {
            get {
                return ResourceManager.GetString("ProgressAutoSaving_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しない.
        /// </summary>
        internal static string ProgressAutoSaving_Disable {
            get {
                return ResourceManager.GetString("ProgressAutoSaving_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1時間ごと.
        /// </summary>
        internal static string ProgressAutoSaving_Hourly {
            get {
                return ResourceManager.GetString("ProgressAutoSaving_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のツール・ブラウザで利用しているポート番号を指定します。.
        /// </summary>
        internal static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動プロキシ設定スクリプトを保存し、設定用URLをクリップボードにコピーしました。
        ///所定の位置に貼り付けてください。.
        /// </summary>
        internal static string ProxyScriptSaved {
            get {
                return ResourceManager.GetString("ProxyScriptSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品質.
        /// </summary>
        internal static string QualitySelect {
            get {
                return ResourceManager.GetString("QualitySelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashの品質を設定します。
        ///既定値は high です。.
        /// </summary>
        internal static string QualitySelectHint {
            get {
                return ResourceManager.GetString("QualitySelectHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務.
        /// </summary>
        internal static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコードの自動保存：.
        /// </summary>
        internal static string RecordAutoSaving {
            get {
                return ResourceManager.GetString("RecordAutoSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1日ごと.
        /// </summary>
        internal static string RecordAutoSaving_Daily {
            get {
                return ResourceManager.GetString("RecordAutoSaving_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to しない.
        /// </summary>
        internal static string RecordAutoSaving_Disable {
            get {
                return ResourceManager.GetString("RecordAutoSaving_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1時間ごと.
        /// </summary>
        internal static string RecordAutoSaving_Hourly {
            get {
                return ResourceManager.GetString("RecordAutoSaving_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レジストリ.
        /// </summary>
        internal static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to プロキシをシステムに登録し、自動的に通信できるようにします。
        ///プロキシ設定が不要になりますが、副作用があるため注意してご利用ください。
        ///詳細はオンラインヘルプを参照してください。.
        /// </summary>
        internal static string RegSystemProxyHint {
            get {
                return ResourceManager.GetString("RegSystemProxyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべての通信ファイルを保存します。.
        /// </summary>
        internal static string SaveAllConnectionFiles {
            get {
                return ResourceManager.GetString("SaveAllConnectionFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIのRequest部を保存します。.
        /// </summary>
        internal static string SaveAPIRequests {
            get {
                return ResourceManager.GetString("SaveAPIRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIのResponse部を保存します。.
        /// </summary>
        internal static string SaveAPIResponses {
            get {
                return ResourceManager.GetString("SaveAPIResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーが発生した際に記録を残します。
        ///記録されたファイルを送信していただければバグ修正に役立てることができます。
        ///デフォルトでは実行フォルダ内 ErrorReport フォルダに保存されます。.
        /// </summary>
        internal static string SaveErrorHint {
            get {
                return ResourceManager.GetString("SaveErrorHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラーレポートを保存する.
        /// </summary>
        internal static string SaveErrorReport {
            get {
                return ResourceManager.GetString("SaveErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存先.
        /// </summary>
        internal static string SaveLocation {
            get {
                return ResourceManager.GetString("SaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログをファイルに保存する.
        /// </summary>
        internal static string SaveLog {
            get {
                return ResourceManager.GetString("SaveLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 指定されたフォルダは存在しません。.
        /// </summary>
        internal static string SavePathDoesNotExist {
            get {
                return ResourceManager.GetString("SavePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動プロキシ設定スクリプトを保存する.
        /// </summary>
        internal static string SaveProxyScriptDialog {
            get {
                return ResourceManager.GetString("SaveProxyScriptDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通信内容を保存する.
        /// </summary>
        internal static string SaveReceivedData {
            get {
                return ResourceManager.GetString("SaveReceivedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWFファイルを保存します。.
        /// </summary>
        internal static string SaveSWF {
            get {
                return ResourceManager.GetString("SaveSWF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to シーン.
        /// </summary>
        internal static string Scene {
            get {
                return ResourceManager.GetString("Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショット.
        /// </summary>
        internal static string Screenshot {
            get {
                return ResourceManager.GetString("Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 秒.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これ統計データベースに送信する.
        /// </summary>
        internal static string SendData {
            get {
                return ResourceManager.GetString("SendData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦名列のソート順：.
        /// </summary>
        internal static string ShipNameSortMethod {
            get {
                return ResourceManager.GetString("ShipNameSortMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to あいうえお順.
        /// </summary>
        internal static string ShipNameSortMethod_Alphabet {
            get {
                return ResourceManager.GetString("ShipNameSortMethod_Alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 図鑑番号順.
        /// </summary>
        internal static string ShipNameSortMethod_Number {
            get {
                return ResourceManager.GetString("ShipNameSortMethod_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPバーを短縮し、スペースを節約します。.
        /// </summary>
        internal static string ShortenHPHint {
            get {
                return ResourceManager.GetString("ShortenHPHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 泊地修理タイマを表示する.
        /// </summary>
        internal static string ShowAnchorageRepairingTimer {
            get {
                return ResourceManager.GetString("ShowAnchorageRepairingTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊一覧の泊地修理タイマを表示するかを指定します。.
        /// </summary>
        internal static string ShowAnchorageRepairingTimer_Tooltip {
            get {
                return ResourceManager.GetString("ShowAnchorageRepairingTimer_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next. を表示する.
        /// </summary>
        internal static string ShowNextXP {
            get {
                return ResourceManager.GetString("ShowNextXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ネタバレを許可する.
        /// </summary>
        internal static string ShowSpoilers {
            get {
                return ResourceManager.GetString("ShowSpoilers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開発したアイテム名やドロップ艦名などのログを記録するかを指定します。
        ///先にわかってしまうことが気になる方は無効にしてください。.
        /// </summary>
        internal static string ShowSpoilersHint {
            get {
                return ResourceManager.GetString("ShowSpoilersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下部のステータスバー(所属艦数など)を表示するかを指定します。
        ///わずかですが表示行数を増やすことができます。.
        /// </summary>
        internal static string ShowStatusbarHint {
            get {
                return ResourceManager.GetString("ShowStatusbarHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最前面に表示する.
        /// </summary>
        internal static string StayOnTop {
            get {
                return ResourceManager.GetString("StayOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to サブフォント.
        /// </summary>
        internal static string Subfont {
            get {
                return ResourceManager.GetString("Subfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大破進撃.
        /// </summary>
        internal static string TaihaAdvance {
            get {
                return ResourceManager.GetString("TaihaAdvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＊再起動後に反映されます。.
        /// </summary>
        internal static string TakeEffectOnRestart {
            get {
                return ResourceManager.GetString("TakeEffectOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーマ.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to テーマ変更は再起動後にすべて反映されます。.
        /// </summary>
        internal static string ThemeRestartWarning {
            get {
                return ResourceManager.GetString("ThemeRestartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下.
        /// </summary>
        internal static string ToolMenuAlignment_Bottom {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非表示.
        /// </summary>
        internal static string ToolMenuAlignment_Invisible {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左.
        /// </summary>
        internal static string ToolMenuAlignment_Left {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右.
        /// </summary>
        internal static string ToolMenuAlignment_Right {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上.
        /// </summary>
        internal static string ToolMenuAlignment_Top {
            get {
                return ResourceManager.GetString("ToolMenuAlignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツールメニューの配置：.
        /// </summary>
        internal static string ToolMenuDockStyle {
            get {
                return ResourceManager.GetString("ToolMenuDockStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これに接続してから操作してください。.
        /// </summary>
        internal static string TryAgainAfterConnect {
            get {
                return ResourceManager.GetString("TryAgainAfterConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バーの色を滑らかに変化させる.
        /// </summary>
        internal static string UI_BarColorMorphing {
            get {
                return ResourceManager.GetString("UI_BarColorMorphing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遂行中のみ表示する.
        /// </summary>
        internal static string UnderWayOnly {
            get {
                return ResourceManager.GetString("UnderWayOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＊未実装です＊.
        /// </summary>
        internal static string Unimplemented {
            get {
                return ResourceManager.GetString("Unimplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他のプロキシを利用するツール・ブラウザと連携する際に利用します。.
        /// </summary>
        internal static string UseProxyHint {
            get {
                return ResourceManager.GetString("UseProxyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムプロキシを利用.
        /// </summary>
        internal static string UseSystemProxy {
            get {
                return ResourceManager.GetString("UseSystemProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to システムのプロキシ設定を利用します。.
        /// </summary>
        internal static string UseSystemProxyTooltip {
            get {
                return ResourceManager.GetString("UseSystemProxyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音量：.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィークリー.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウ.
        /// </summary>
        internal static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザバージョンをレジストリに書き込みました。削除したい場合は「設定→サブウィンドウ→ブラウザ2→削除」を押してください。.
        /// </summary>
        internal static string WriteRegistry {
            get {
                return ResourceManager.GetString("WriteRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム倍率.
        /// </summary>
        internal static string ZoomRate {
            get {
                return ResourceManager.GetString("ZoomRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴったり.
        /// </summary>
        internal static string ZoomToFit {
            get {
                return ResourceManager.GetString("ZoomToFit", resourceCulture);
            }
        }
    }
}
