//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Browser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Browser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下(&amp;B).
        /// </summary>
        internal static string Alignment_Bottom {
            get {
                return ResourceManager.GetString("Alignment_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非表示(&amp;I).
        /// </summary>
        internal static string Alignment_Invisible {
            get {
                return ResourceManager.GetString("Alignment_Invisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 左(&amp;L).
        /// </summary>
        internal static string Alignment_Left {
            get {
                return ResourceManager.GetString("Alignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 右(&amp;R).
        /// </summary>
        internal static string Alignment_Right {
            get {
                return ResourceManager.GetString("Alignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上(&amp;T).
        /// </summary>
        internal static string Alignment_Top {
            get {
                return ResourceManager.GetString("Alignment_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // KCRDBと競合しないように同じように処理
        ///try {
        ///	var hideStyle = {width:&quot;0px&quot;,height:&quot;0px&quot;,visibility:&quot;hidden&quot;,display:&quot;none&quot;};
        ///	var fillStyle = {margin:&quot;0px&quot;,padding:&quot;0px&quot;,position:&quot;fixed&quot;,left:&quot;0px&quot;,top:&quot;0px&quot;,width:&quot;100%&quot;,height:&quot;100%&quot;,overflow:&quot;hidden&quot;};
        ///	var jqBody=document.body;
        ///	$(jqBody).css(&quot;zoom&quot;,&quot;normal&quot;);
        ///	$(jqBody).css({margin:&quot;0px&quot;,padding:&quot;0px&quot;,overflow:&quot;hidden&quot;});
        ///	$(&quot;#spacing_top&quot;).css(hideStyle);
        ///	$(&quot;#adFlashWrap&quot;).css(fillStyle);
        ///	$(&quot;#wsFlashWrap&quot;).css(fillStyle);
        ///	$(&quot;#flashWrap&quot;).css(fillStyle);
        ///	var elmE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FrameScript {
            get {
                return ResourceManager.GetString("FrameScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to その他.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置(&amp;A).
        /// </summary>
        internal static string Other_Alignment {
            get {
                return ResourceManager.GetString("Other_Alignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スタイルシートを適用する.
        /// </summary>
        internal static string Other_ApplyStyleSheet {
            get {
                return ResourceManager.GetString("Other_ApplyStyleSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to キャッシュのクリア(&amp;C).
        /// </summary>
        internal static string Other_ClearCache {
            get {
                return ResourceManager.GetString("Other_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミュート(&amp;M).
        /// </summary>
        internal static string Other_Mute {
            get {
                return ResourceManager.GetString("Other_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移動(&amp;N)....
        /// </summary>
        internal static string Other_Navigate {
            get {
                return ResourceManager.GetString("Other_Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインページへ移動(&amp;L).
        /// </summary>
        internal static string Other_NavigateToLogInPage {
            get {
                return ResourceManager.GetString("Other_NavigateToLogInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新(&amp;R).
        /// </summary>
        internal static string Other_Refresh {
            get {
                return ResourceManager.GetString("Other_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地域制限クッキーを設定.
        /// </summary>
        internal static string Other_RegionCookie {
            get {
                return ResourceManager.GetString("Other_RegionCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショット(&amp;S).
        /// </summary>
        internal static string Other_Screenshot {
            get {
                return ResourceManager.GetString("Other_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム(&amp;Z).
        /// </summary>
        internal static string Other_Zoom {
            get {
                return ResourceManager.GetString("Other_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現在%.
        /// </summary>
        internal static string Other_Zoom_Current {
            get {
                return ResourceManager.GetString("Other_Zoom_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ぴったり.
        /// </summary>
        internal static string Other_Zoom_Fit {
            get {
                return ResourceManager.GetString("Other_Zoom_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // KCRDBと競合しないように同じように処理
        ///try {
        ///	var hideStyle = {width:&quot;0px&quot;,height:&quot;0px&quot;,visibility:&quot;hidden&quot;,display:&quot;none&quot;};
        ///	var fillStyle = {margin:&quot;0px&quot;,padding:&quot;0px&quot;,position:&quot;fixed&quot;,left:&quot;0px&quot;,top:&quot;0px&quot;,width:&quot;100%&quot;,height:&quot;100%&quot;,overflow:&quot;hidden&quot;};
        ///	$(document.body).css({margin:&quot;0px&quot;,padding:&quot;0px&quot;,overflow:&quot;hidden&quot;});
        ///	$(&quot;img&quot;).css(hideStyle);
        ///	//$(&quot;#dmm_ntgnavi&quot;).css(hideStyle);
        ///	$(&quot;#dmm-ntgnavi-renew&quot;).css(hideStyle);
        ///	$(&quot;#w&quot;).css(fillStyle);
        ///	$(&quot;#main-ntg&quot;).css(fillStyle);
        ///	$(&quot;#page&quot;).css(fillStyle);
        ///	$(&quot;#area-g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PageScript {
            get {
                return ResourceManager.GetString("PageScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツールメニューを表示.
        /// </summary>
        internal static string ShowToolMenu {
            get {
                return ResourceManager.GetString("ShowToolMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ミュート.
        /// </summary>
        internal static string Strip_Mute {
            get {
                return ResourceManager.GetString("Strip_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログインページへ移動.
        /// </summary>
        internal static string Strip_NavigateToLogInPage {
            get {
                return ResourceManager.GetString("Strip_NavigateToLogInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        internal static string Strip_Refresh {
            get {
                return ResourceManager.GetString("Strip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to スクリーンショット.
        /// </summary>
        internal static string Strip_ScreenShot {
            get {
                return ResourceManager.GetString("Strip_ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ズーム.
        /// </summary>
        internal static string Strip_Zoom {
            get {
                return ResourceManager.GetString("Strip_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 七四式電子観測儀 ブラウザ.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
