//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties.Window {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.Window.FormMain", typeof(FormMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認.
        /// </summary>
        public static string ConfirmatonCaption {
            get {
                return ResourceManager.GetString("ConfirmatonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to デバッグ(&amp;D).
        /// </summary>
        public static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 古いAPIデータを削除(&amp;D).
        /// </summary>
        public static string Debug_DeleteOldAPI {
            get {
                return ResourceManager.GetString("Debug_DeleteOldAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイルからAPIをロード(&amp;L)....
        /// </summary>
        public static string Debug_LoadAPIFromFile {
            get {
                return ResourceManager.GetString("Debug_LoadAPIFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧 api_start2から深海棲艦を復元(&amp;A)....
        /// </summary>
        public static string Debug_LoadDataFromOld {
            get {
                return ResourceManager.GetString("Debug_LoadDataFromOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIリストをロード(&amp;I)....
        /// </summary>
        public static string Debug_LoadInitialAPI {
            get {
                return ResourceManager.GetString("Debug_LoadInitialAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧 api_start2 からレコードを構築(&amp;O)....
        /// </summary>
        public static string Debug_LoadRecordFromOld {
            get {
                return ResourceManager.GetString("Debug_LoadRecordFromOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船リソースをリネーム(&amp;R)....
        /// </summary>
        public static string Debug_RenameShipResource {
            get {
                return ResourceManager.GetString("Debug_RenameShipResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備データが読み込まれていません。.
        /// </summary>
        public static string EquipmentDataNotLoaded {
            get {
                return ResourceManager.GetString("EquipmentDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エラー.
        /// </summary>
        public static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} を終了しますか？.
        /// </summary>
        public static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザを開くのに失敗しました.
        /// </summary>
        public static string FailedToOpenBrowser {
            get {
                return ResourceManager.GetString("FailedToOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ファイル(&amp;F).
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 終了(&amp;X).
        /// </summary>
        public static string File_Close {
            get {
                return ResourceManager.GetString("File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定(&amp;C)....
        /// </summary>
        public static string File_Configuration {
            get {
                return ResourceManager.GetString("File_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト(&amp;L).
        /// </summary>
        public static string File_Layout {
            get {
                return ResourceManager.GetString("File_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 別のファイルへ保存(&amp;C)....
        /// </summary>
        public static string File_Layout_Change {
            get {
                return ResourceManager.GetString("File_Layout_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 復元(&amp;L).
        /// </summary>
        public static string File_Layout_Load {
            get {
                return ResourceManager.GetString("File_Layout_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウトのロック(&amp;T).
        /// </summary>
        public static string File_Layout_LockLayout {
            get {
                return ResourceManager.GetString("File_Layout_LockLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 別のファイルから復元(&amp;O)....
        /// </summary>
        public static string File_Layout_Open {
            get {
                return ResourceManager.GetString("File_Layout_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存(&amp;S).
        /// </summary>
        public static string File_Layout_Save {
            get {
                return ResourceManager.GetString("File_Layout_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最前面に表示(&amp;M).
        /// </summary>
        public static string File_Layout_TopMost {
            get {
                return ResourceManager.GetString("File_Layout_TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通知(&amp;N).
        /// </summary>
        public static string File_Notification {
            get {
                return ResourceManager.GetString("File_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to すべての通知をミュート(&amp;M).
        /// </summary>
        public static string File_Notification_MuteAll {
            get {
                return ResourceManager.GetString("File_Notification_MuteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レコード(&amp;R).
        /// </summary>
        public static string File_Record {
            get {
                return ResourceManager.GetString("File_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ロード(&amp;L).
        /// </summary>
        public static string File_Record_Load {
            get {
                return ResourceManager.GetString("File_Record_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to セーブ(&amp;S).
        /// </summary>
        public static string File_Record_Save {
            get {
                return ResourceManager.GetString("File_Record_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ(&amp;H).
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ディスコードでの参加.
        /// </summary>
        public static string Help_Discord {
            get {
                return ResourceManager.GetString("Help_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to オンラインヘルプ(&amp;H)....
        /// </summary>
        public static string Help_Help {
            get {
                return ResourceManager.GetString("Help_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 問題を報告する.
        /// </summary>
        public static string Help_Issue {
            get {
                return ResourceManager.GetString("Help_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to アップデートのチェック.
        /// </summary>
        public static string Help_Update {
            get {
                return ResourceManager.GetString("Help_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to バージョン情報(&amp;V).
        /// </summary>
        public static string Help_Version {
            get {
                return ResourceManager.GetString("Help_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        public static string HelpCaption {
            get {
                return ResourceManager.GetString("HelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Preparing....
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} からウィンドウ レイアウトを復元しました。.
        /// </summary>
        public static string LayoutLoaded {
            get {
                return ResourceManager.GetString("LayoutLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部ブラウザでオンラインヘルプを開きます。
        ///よろしいですか？.
        /// </summary>
        public static string OpenEOWiki {
            get {
                return ResourceManager.GetString("OpenEOWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト ファイルを開く.
        /// </summary>
        public static string OpenLayoutCaption {
            get {
                return ResourceManager.GetString("OpenLayoutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部ブラウザでオンラインヘルプを開きます。
        ///よろしいですか？.
        /// </summary>
        public static string ReportIssue {
            get {
                return ResourceManager.GetString("ReportIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 問題を報告する.
        /// </summary>
        public static string ReportIssueCaption {
            get {
                return ResourceManager.GetString("ReportIssueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to レイアウト ファイルの保存.
        /// </summary>
        public static string SaveLayoutCaption {
            get {
                return ResourceManager.GetString("SaveLayoutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船データが読み込まれていません。.
        /// </summary>
        public static string ShipDataNotLoaded {
            get {
                return ResourceManager.GetString("ShipDataNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  を起動しています….
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 試製七四式電子観測儀.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール(&amp;T).
        /// </summary>
        public static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備図鑑(&amp;E).
        /// </summary>
        public static string Tool_AlbumMasterEquipment {
            get {
                return ResourceManager.GetString("Tool_AlbumMasterEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船図鑑(&amp;S).
        /// </summary>
        public static string Tool_AlbumMasterShip {
            get {
                return ResourceManager.GetString("Tool_AlbumMasterShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空砲火詳細(&amp;A).
        /// </summary>
        public static string Tool_AntiAirDefense {
            get {
                return ResourceManager.GetString("Tool_AntiAirDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基地航空隊編成(&amp;B).
        /// </summary>
        public static string Tool_BaseAirCorpsSimulation {
            get {
                return ResourceManager.GetString("Tool_BaseAirCorpsSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 建造記録(&amp;R).
        /// </summary>
        public static string Tool_ConstructionRecord {
            get {
                return ResourceManager.GetString("Tool_ConstructionRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開発記録(&amp;V).
        /// </summary>
        public static string Tool_DevelopmentRecord {
            get {
                return ResourceManager.GetString("Tool_DevelopmentRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ドロップ記録(&amp;D).
        /// </summary>
        public static string Tool_DropRecord {
            get {
                return ResourceManager.GetString("Tool_DropRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装備一覧(&amp;Q).
        /// </summary>
        public static string Tool_EquipmentList {
            get {
                return ResourceManager.GetString("Tool_EquipmentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 必要経験値計算(&amp;X).
        /// </summary>
        public static string Tool_ExpChecker {
            get {
                return ResourceManager.GetString("Tool_ExpChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 遠征可否チェック(&amp;M).
        /// </summary>
        public static string Tool_ExpeditionCheck {
            get {
                return ResourceManager.GetString("Tool_ExpeditionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to エクストラブラウザ.
        /// </summary>
        public static string Tool_ExtraBrowser {
            get {
                return ResourceManager.GetString("Tool_ExtraBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編成画像出力(&amp;F).
        /// </summary>
        public static string Tool_FleetImageGenerator {
            get {
                return ResourceManager.GetString("Tool_FleetImageGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦これ進捗.
        /// </summary>
        public static string Tool_KancolleProgress {
            get {
                return ResourceManager.GetString("Tool_KancolleProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 資源チャート(&amp;C).
        /// </summary>
        public static string Tool_ResourceChart {
            get {
                return ResourceManager.GetString("Tool_ResourceChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 七四式v{0}が登場.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示(&amp;V).
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工廠(&amp;A).
        /// </summary>
        public static string View_Arsenal {
            get {
                return ResourceManager.GetString("View_Arsenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基地航空隊(&amp;S).
        /// </summary>
        public static string View_BaseAirCorps {
            get {
                return ResourceManager.GetString("View_BaseAirCorps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘(&amp;B).
        /// </summary>
        public static string View_Battle {
            get {
                return ResourceManager.GetString("View_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ブラウザ(&amp;M).
        /// </summary>
        public static string View_Browser {
            get {
                return ResourceManager.GetString("View_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 羅針盤(&amp;C).
        /// </summary>
        public static string View_Compass {
            get {
                return ResourceManager.GetString("View_Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入渠(&amp;D).
        /// </summary>
        public static string View_Dock {
            get {
                return ResourceManager.GetString("View_Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊(&amp;F).
        /// </summary>
        public static string View_Fleet {
            get {
                return ResourceManager.GetString("View_Fleet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #&amp;1.
        /// </summary>
        public static string View_Fleet_1 {
            get {
                return ResourceManager.GetString("View_Fleet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #&amp;2.
        /// </summary>
        public static string View_Fleet_2 {
            get {
                return ResourceManager.GetString("View_Fleet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #&amp;3.
        /// </summary>
        public static string View_Fleet_3 {
            get {
                return ResourceManager.GetString("View_Fleet_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #&amp;4.
        /// </summary>
        public static string View_Fleet_4 {
            get {
                return ResourceManager.GetString("View_Fleet_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦隊一覧(&amp;O).
        /// </summary>
        public static string View_FleetOverview {
            get {
                return ResourceManager.GetString("View_FleetOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編成プリセット(&amp;P).
        /// </summary>
        public static string View_FleetPreset {
            get {
                return ResourceManager.GetString("View_FleetPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 司令部(&amp;H).
        /// </summary>
        public static string View_Headquarters {
            get {
                return ResourceManager.GetString("View_Headquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報(&amp;I).
        /// </summary>
        public static string View_Information {
            get {
                return ResourceManager.GetString("View_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON(&amp;J).
        /// </summary>
        public static string View_Json {
            get {
                return ResourceManager.GetString("View_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログ(&amp;L).
        /// </summary>
        public static string View_Log {
            get {
                return ResourceManager.GetString("View_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務(&amp;Q).
        /// </summary>
        public static string View_Quest {
            get {
                return ResourceManager.GetString("View_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 艦船グループ(&amp;G).
        /// </summary>
        public static string View_ShipGroup {
            get {
                return ResourceManager.GetString("View_ShipGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ウィンドウキャプチャ(&amp;W).
        /// </summary>
        public static string WindowCapture {
            get {
                return ResourceManager.GetString("WindowCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て再検索して取り込む(&amp;S).
        /// </summary>
        public static string WindowCapture_AttachAll {
            get {
                return ResourceManager.GetString("WindowCapture_AttachAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全てのウィンドウを開放(&amp;R).
        /// </summary>
        public static string WindowCapture_DetachAll {
            get {
                return ResourceManager.GetString("WindowCapture_DetachAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to コントロールウィンドウ(&amp;C).
        /// </summary>
        public static string WindowCapture_SubWindow {
            get {
                return ResourceManager.GetString("WindowCapture_SubWindow", resourceCulture);
            }
        }
    }
}
