//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties.Window {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormQuest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormQuest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.Window.FormQuest", typeof(FormQuest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務はすべて翻訳されています.
        /// </summary>
        public static string AllQuestsAreTranslated {
            get {
                return ResourceManager.GetString("AllQuestsAreTranslated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 達成！.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務『{0}』の進捗を変更することはできません。.
        /// </summary>
        public static string FailedToChangeQuestProgress {
            get {
                return ResourceManager.GetString("FailedToChangeQuestProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務の検索に失敗しました.
        /// </summary>
        public static string FailedToOpenKancolleWiki {
            get {
                return ResourceManager.GetString("FailedToOpenKancolleWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務名の DuckDuckGo 検索に失敗しました。.
        /// </summary>
        public static string FailedToSearchOnWeb {
            get {
                return ResourceManager.GetString("FailedToSearchOnWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 情報.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務名でDuckDuckGo検索(&amp;G).
        /// </summary>
        public static string LookUpQuestOnWeb {
            get {
                return ResourceManager.GetString("LookUpQuestOnWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 『{0}』でDuckDuckGo検索(&amp;G).
        /// </summary>
        public static string LookUpSpecificQuestOnWeb {
            get {
                return ResourceManager.GetString("LookUpSpecificQuestOnWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務名でwikiwiki検索(&amp;K).
        /// </summary>
        public static string LookUpSpecificQuestOnWiki {
            get {
                return ResourceManager.GetString("LookUpSpecificQuestOnWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務の説明をコピー(&amp;D).
        /// </summary>
        public static string ManuMain_QuestDescription {
            get {
                return ResourceManager.GetString("ManuMain_QuestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務タイトルをコピー(&amp;T).
        /// </summary>
        public static string ManuMain_QuestTitle {
            get {
                return ResourceManager.GetString("ManuMain_QuestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻訳されていない任務データをコピー(&amp;N).
        /// </summary>
        public static string ManuMain_QuestTranslate {
            get {
                return ResourceManager.GetString("ManuMain_QuestTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務名でwikiwiki検索(&amp;K).
        /// </summary>
        public static string MenuMain_KcwikiQuest {
            get {
                return ResourceManager.GetString("MenuMain_KcwikiQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表示フィルタ(&amp;Q).
        /// </summary>
        public static string MenuMain_QuestFilter {
            get {
                return ResourceManager.GetString("MenuMain_QuestFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 進捗リセット(&amp;R).
        /// </summary>
        public static string MenuProgress_Reset {
            get {
                return ResourceManager.GetString("MenuProgress_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (未取得の任務 x {0}).
        /// </summary>
        public static string OtherQuests {
            get {
                return ResourceManager.GetString("OtherQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ページ.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務削除の確認.
        /// </summary>
        public static string QuestResetConfirmationCaption {
            get {
                return ResourceManager.GetString("QuestResetConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 任務{0}を一覧から削除し、進捗をリセットします。
        ///よろしいですか？
        ///(艦これ本体の任務画面を開くと正しく更新されます。).
        /// </summary>
        public static string QuestResetConfirmationText {
            get {
                return ResourceManager.GetString("QuestResetConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +艦これ.
        /// </summary>
        public static string SearchEngineKancolleSpecifier {
            get {
                return ResourceManager.GetString("SearchEngineKancolleSpecifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wikiwiki.jp/kancolle/任務#{0}.
        /// </summary>
        public static string SearchLinkWiki {
            get {
                return ResourceManager.GetString("SearchLinkWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to site:wikiwiki.jp/kancolle.
        /// </summary>
        public static string SearchOnWikiQuery {
            get {
                return ResourceManager.GetString("SearchOnWikiQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (未取得).
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
