//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties.Window.Dialog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogShipGroupSortOrder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogShipGroupSortOrder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.Window.Dialog.DialogShipGroupSortOrder", typeof(DialogShipGroupSortOrder).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動ソートする.
        /// </summary>
        public static string AutoSortFlag {
            get {
                return ResourceManager.GetString("AutoSortFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; 全て.
        /// </summary>
        public static string ButtonLeftAll {
            get {
                return ResourceManager.GetString("ButtonLeftAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全て &gt;&gt;.
        /// </summary>
        public static string ButtonRightAll {
            get {
                return ResourceManager.GetString("ButtonRightAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列名.
        /// </summary>
        public static string DisabledView_Name {
            get {
                return ResourceManager.GetString("DisabledView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列名.
        /// </summary>
        public static string EnabledView_Name {
            get {
                return ResourceManager.GetString("EnabledView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 順.
        /// </summary>
        public static string EnabledView_SortDirection {
            get {
                return ResourceManager.GetString("EnabledView_SortDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EnabledView_SortDirectionToolTip {
            get {
                return ResourceManager.GetString("EnabledView_SortDirectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自動ソート順.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
