//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserverTypes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EquipmentTypeGroups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EquipmentTypeGroups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserverTypes.Properties.EquipmentTypeGroups", typeof(EquipmentTypeGroups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜水.
        /// </summary>
        public static string ASWGears {
            get {
                return ResourceManager.GetString("ASWGears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 爆撃機.
        /// </summary>
        public static string Bomber {
            get {
                return ResourceManager.GetString("Bomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘機.
        /// </summary>
        public static string Fighter {
            get {
                return ResourceManager.GetString("Fighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 陸攻.
        /// </summary>
        public static string LandBasedBombers {
            get {
                return ResourceManager.GetString("LandBasedBombers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 陸戦.
        /// </summary>
        public static string LandBasedFighters {
            get {
                return ResourceManager.GetString("LandBasedFighters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主砲.
        /// </summary>
        public static string MainGun {
            get {
                return ResourceManager.GetString("MainGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 他.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 電探.
        /// </summary>
        public static string Radar {
            get {
                return ResourceManager.GetString("Radar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偵察機.
        /// </summary>
        public static string SeaplanesAndRecons {
            get {
                return ResourceManager.GetString("SeaplanesAndRecons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 副砲.
        /// </summary>
        public static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 魚雷.
        /// </summary>
        public static string Torpedo {
            get {
                return ResourceManager.GetString("Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 攻撃機.
        /// </summary>
        public static string TorpedoBomber {
            get {
                return ResourceManager.GetString("TorpedoBomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輸送.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
    }
}
