//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserverTypes.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShipTypeGroups {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShipTypeGroups() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserverTypes.Properties.ShipTypeGroups", typeof(ShipTypeGroups).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 補助艦.
        /// </summary>
        public static string Auxiliaries {
            get {
                return ResourceManager.GetString("Auxiliaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦艦.
        /// </summary>
        public static string Battleships {
            get {
                return ResourceManager.GetString("Battleships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空母.
        /// </summary>
        public static string Carriers {
            get {
                return ResourceManager.GetString("Carriers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 駆逐艦.
        /// </summary>
        public static string Destroyers {
            get {
                return ResourceManager.GetString("Destroyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海防艦.
        /// </summary>
        public static string Escorts {
            get {
                return ResourceManager.GetString("Escorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重巡.
        /// </summary>
        public static string HeavyCruisers {
            get {
                return ResourceManager.GetString("HeavyCruisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 軽巡.
        /// </summary>
        public static string LightCruisers {
            get {
                return ResourceManager.GetString("LightCruisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 潜水艦.
        /// </summary>
        public static string Submarines {
            get {
                return ResourceManager.GetString("Submarines", resourceCulture);
            }
        }
    }
}
